dbos-inc/dbos-transact-ts

examples/hello/.npmrc
The "Hello, World!" example created by `npx operon init` now pulls from our [public npm repository](https://www.npmjs.com/package/@dbos-inc/operon).
=> Remove .npmrc 

.eslintrc.cjs, .vscode/launch.json, examples/hello/tsconfig.json, src/operon-runtime/cli.ts, src/operon-runtime/config.ts, src/operon-runtime/runtime.ts, tests/operon-runtime/config.test.ts, tests/operon-runtime/runtime.test.ts
~still working on tests~
FYI, this PR has two somewhat unrelated changes:
* Update linter config to ignore `examples/` folder 
* rename `localRuntimeConfig` to `runtimeConfig`
=> Support entrypoint CLI/local runtime config option

src/context.ts, src/error.ts, src/operon-runtime/config.ts, src/operon-runtime/runtime.ts, src/testing/testing_runtime.ts, tests/decorator.test.ts, tests/operon-runtime/config.test.ts, tests/testing/testing_runtime.test.ts
Now we can use `getConfig` as follows:
Configuration file:
```yaml
database:
...
application:
foo:
- bar
- baz
```
User code:
```typescript
interface myProperties {
list: string[];
}
...
@GetApi("/greeting/:name")
static async helloHandler(ctx: HandlerContext, name: string) {
const fooProperty = ctx.getConfig<myProperties>("foo");
}
```
=> make getConfig return a generic type

src/foundationdb/fdb_system_database.ts, src/operon.ts, src/system_database.ts, src/workflow.ts, tests/foundationdb/foundationdb.test.ts, tests/operon.test.ts
This PR adds `getEvent()` and `retrieveWorkflow()` methods to the `WorkflowContext` public interface, and guarantees `getEvent()` and `handle.getStatus()` to be executed exactly-once inside workflows.
Previously, these two operations may return different results if retried (e.g., due to timeouts or workflow status change), which may violate our OAOO guarantees.
Specifically, this PR:
- Updates `getEvent()` and `getWorkflowStatus()`in system databases (both PG and FDB) to check and record the output to guarantee OAOO (only if called within a workflow).
- Use `callerUUID` and `callerFunctionID` to differentiate function calls inside vs. outside of a workflow. We only guarantee OAOO when `getEvent()` or `getStatus()` are called within a workflow.
- Adds a test in both operon.test.ts and …
=> OAOO for getEvent and getWorkflowStatus within a workflow

.gitignore, package-lock.json, package.json, src/operon-runtime/cli.ts, src/operon-runtime/deploy.ts, src/operon-runtime/login.ts
This PR implements `npx operon login -u <username>`, which currently takes in a user name and creates a "valid but fake" JWT token to be used in `npx operon deploy`. This PR removes the previously hard coded JWT token in deploy.
`login` stores the generated token in a local file `.operon/credentials`, and `deploy` reads the token from that file.
In the future, we will integrate with a 3rd-party auth system (e.g., Okta) and we will re-direct users to login through the auth system and obtain a real JWT token there.
=> Operon CLI login

src/cloud-cli/deploy.ts, src/cloud-cli/login.ts
Depends on https://github.com/dbos-inc/operon-cloud/pull/40
This PR:
- Adds the username to the `.operon/credentials` file
- Uses said username to register applications & deploy code.
- Offers slightly cleaner Axios error handling
Tested:
=> update login & deploy CLI to use usernames

.github/workflows/publish_npm.yml
This Github action publishes a package to npm with a proper tag:
- Only `release/*` branches will be tagged as `latest`.
- Main branch will be tagged as `preview`.
- Publishes from other branches will be tagged as `test`.
When we run `npm install @dbos-inc/operon` it will only install the latest release version, not the `preview` or `test` versions. Please the published versions here: https://www.npmjs.com/package/@dbos-inc/operon?activeTab=versions
This action currently can only be triggered manually.
Another cool thing about `JS-DevTools/npm-publish@v3` action is that it can automatically skip a publish if the version already exists on NPM. So we don't need to worry about version conflicts.
=> Create an npm publish action

src/cloud-cli/cli.ts, src/cloud-cli/delete.ts, src/cloud-cli/deploy.ts, src/cloud-cli/register.ts
This PR implements `npx operon-cloud register` and `npx operon-cloud delete` in the cloud CLI.
- Register currently sends a request to register a user in the control plane, and then log in as that user if registration succeeds. We will eventually redirect users to a 3rd-party registration/login page.
- Delete sends a request to delete a deployed application of a logged in user.
Tested on a bare-metal instance and it works well.
=> Cloud CLI Register & Delete

package-lock.json, src/httpServer/middleware.ts, src/httpServer/server.ts, src/user_database.ts, tests/helpers.ts, tests/knex.test.ts, tests/prisma.test.ts, tests/prisma/schema.prisma, tests/typeorm.test.ts
Provide additional functions for middleware, including database access, logging, and configuration information.
This revealed a need for a better client interface to queries, that was more in line with the experience expected for those clients.  I have stubbed these in, except for Prisma (currently using transaction unnecessarily).
This needs considerably more test coverage, but you can see a test for TypeORM to get an idea of what is going on.
=> Database access to middleware

src/httpServer/server.ts, tests/httpServer/server.test.ts
This makes it possible for OpenAPI clients to get the custom error message from Operon errors in a typical way.
Took some work to convince supertest to do this.
=> Set HTTP error message in typical way for OpenAPI

src/operon-runtime/config.ts, tests/operon-runtime/config.test.ts
Remove the envsubst dependency from Operon.  For now, replacing it with a regex matching ${VAR_NAME} style placeholders.
=> Remove Envsubst Dependency

src/cloud-cli/cli.ts, src/cloud-cli/delete.ts, src/cloud-cli/deploy.ts, src/cloud-cli/monitor.ts, src/cloud-cli/utils.ts
This PR adds the `npx operon-cloud logs -n <appName>` command, which retrieves FC microVM logs from the cloud.
Manually tested on a bare-metal machine.
=> Operon-cloud "logs" Command

src/operon-runtime/openApi.ts, tests/operon-runtime/openapi.test.ts
@qianl15 reminded me that all HTTP handlers support an [optional `operon-workflowuuid` header](https://github.com/dbos-inc/operon/blob/devhawk/headerWorkflowUUID/src/httpServer/server.ts#L144) for idempotent requests. This PR adds an optional header parameter to every OpenAPI path operation:
```yaml
- name: operon-workflowuuid
in: header
required: false
schema:
type: string
```
Theoretically, this name could collide with a parameter name in the user's code. Unlikely but possible. @qianl15 suggested reserving all identifiers starting with "operon" for our use. I haven't implemented that check yet, but I think it would be a reasonable idea.
=> add optional parameter for Operon workflow UUID header

src/operon-runtime/config.ts, tests/operon-runtime/config.test.ts
Remove the envsubst dependency from Operon. For now, replacing it with a regex matching ${VAR_NAME} style placeholders.
=> Remove Envsubst Dependency (#161)

examples/hello/knexfile.ts, src/cloud-cli/applications/deploy-app-code.ts, src/cloud-cli/cli.ts, src/operon-runtime/cli.ts, src/operon-runtime/config.ts, src/testing/testing_runtime.ts, tests/operon-runtime/config.test.ts
A previous PR changed a function name used in demo apps' `knexfile`. Today we don't tag demo apps and their main branch has to be compatible with whatever version of the SDK they import.
=> Update config loading function names to become compatible again with demo apps.

examples/hello/start_postgres_docker.sh, schemas/user_db_schema.ts, src/httpServer/server.ts, src/operon.ts, src/workflow.ts
This PR implements two things:
1. Record transaction ID (if the transaction contains writes) and transaction snapshot information in `operon.transaction_outputs` table. This table will be exported through WAL to our provenance database.
2. Fix a bug where Operon may crash due to uncaught workflow exceptions. We now keep track of pending workflows using a `pendingWorkflowMap` map. Each workflow adds itself when being invoked and deletes itself from the map when it completes, while catching errors thrown by its executions.
=> Capture transaction info & Handle workflow exceptions

src/user_database.ts, src/workflow.ts
Fixed an issue where some serialization errors would be converted to WorkflowConflictUUID errors and not retried, instead leaving the workflow stuck forever waiting for the fictitious other workflow with the same UUID.
=> Fix Error-Handling Issue

src/cloud-cli/applications/deploy-app-code.ts, src/cloud-cli/applications/index.ts, src/cloud-cli/applications/list-apps.ts, src/cloud-cli/applications/types.ts, src/cloud-cli/applications/update-app.ts, src/cloud-cli/cli.ts, src/operon-runtime/config.ts, src/utils.ts
A subcommand to update applications.
For now, does the most simple thing: ask users to always provide the full intent of the app record, i.e., provide a name and max_vms.  For now, only `max_vms` can be updated. Updating the application name require more uplifting in the backend, which we should not do now.
=> add cloud CLI applications subcommand to update an application

src/user_database.ts, src/workflow.ts, tests/operon.test.ts
This PR fixes the snapshot capturing for read-only transactions and several small bugs.
1. We should capture snapshot information when we first start the transaction not when we flush the result buffer (for read-only transactions, this happens in a different following transaction).
- This PR aims to capture snapshot in a single roundtrip to the DB (because RDS roundtrips are slow), therefore we piggyback this check with the check recorded output query.
- Added a test for snapshot information capture. 
3. We eliminated an unnecessary roundtrip to retrieve transaction ID (`pg_current_xact_id()` also consumes transaction ID which is bad).
4. We also fixed a small issue where read-only knex transactions are not correctly marked as read-only.
=> Fix Snapshot Capture

src/operon.ts, src/system_database.ts
The workflow status buffer now retries failures during flush, so Operon doesn't crash due to a momentary network hiccup.
=> Retry Buffer Flushes

src/dbos-executor.ts, src/workflow.ts, tests/foundationdb/fdb_oaoo.test.ts, tests/foundationdb/foundationdb.test.ts, tests/oaoo.test.ts
This PR fixes a bug in `childWorkflow()` where we didn't correctly pass its own UUID and funcID to the invokedHandle. Therefore, the `getStatus()` method in the invokedHandle wasn't actually OAOO.
This PR also updates the OAOO tests for this potential buggy scenario.
=> Fix OAOO bug for workflow getStatus()

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/debugger/debug_workflow.ts, src/error.ts, src/transaction.ts, src/workflow.ts, tests/dbos.test.ts, tests/helpers.ts, tests/testing/debugger.test.ts
This PR adds initial support for the debug mode. The main goal is to faithfully replay past workflow executions. Under debug mode, everything should be read-only: we skip initialization steps in the database and don't record for OAOO. Instead of connecting to the actual user DB, we connect to a debugger proxy which transforms queries to perform time traveling.
Details:
- Add a CLI option for `npx dbos-sdk start`: `-d, --debug` with the URL of the debug proxy.
- We can only execute a workflow in debug if we can find recorded workflow status and transaction output. Otherwise, we throw an error.
- Create a new workflow context called `WorkflowContextDebug`, which implements debugger specific methods. We currently only support executing transaction functions or child workflows. Will implement …
=> Initial Debugger

src/communicator.ts, src/dbos-executor.ts, src/debugger/debug_workflow.ts, src/testing/testing_runtime.ts, src/workflow.ts, tests/foundationdb/fdb_oaoo.test.ts, tests/oaoo.test.ts, tests/testing/debugger.test.ts
This PR implements the rest of the methods (other than transaction and childWorkflow) in `debug_workflow.ts`, and adds corresponding tests for them. All methods should be read-only, checking recorded output from the system database.
This PR also fixes a minor flaky OAOO test, by waiting for the workflow to finish before retrieving its status.
=> Implement Debug Methods

examples/hello/dbos-config.yaml, src/cloud-cli/cli.ts, src/cloud-cli/userdb.ts, src/dbos-runtime/config.ts
npx dbos-cloud userdb migrate
Notes:
dbos-config.yaml needs to be pointing to the right database.
This means you should have run
npx dbos-cloud userdb create ....... to provision the db
npx dbos-cloud applications configure ........... to update dbos-config.yaml
=> Dbschema migr -- command side

src/cloud-cli/userdb.ts, src/dbos-executor.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts
This PR asynchronously records inputs of temporary workflows so they can easily be replayed by the debugger.
=> Always Record Inputs

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/debug.ts, src/dbos-runtime/runtime.ts, src/testing/testing_runtime.ts
This PR refactors the debug mode CLI. Instead of adding an option in `npx dbos-sdk start`, this PR implements a new CLI command `npx debug`. The idea is to initiate a very simple DBOSExecutor in debug mode and execute the workflow given its UUID, and wait for its result. We can attach a debugger (I tested with the VSCode debugger) to single step through the execution.
```
Usage: dbos-sdk debug [options]
Debug a workflow
Options:
-x, --proxy <string>       Specify the debugger proxy URL [Required]
-u, --uuid <string>        Specify the workflow UUID to debug [Required]
-l, --loglevel <string>    Specify log level
-c, --configfile <string>  Specify the config file path (default: "dbos-config.yaml")
-e, --entrypoint <string>  Specify the entrypoint file path
-h, --help …
```
=> Debug mode CLI

src/dbos-executor.ts, src/debugger/debug_workflow.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts, src/workflow.ts, tests/testing/debugger.test.ts
This PR adds support for replaying temporary workflows. The key idea is to record full workflow status and store transaction/communicator functions. Previously, we don't record metadata for temporary workflows such as the original HTTP request and authenticated roles. This PR adds those metadata for all workflows.
For temporary workflows, we record the name with the format: `temp_workflow-<transaction/external/send>-<function name>`. Then the `executeWorkflowUUID` function parses the name and find the corresponding function.
Add tests to confirm that we can correctly re-execute temporary workflows.
=> Support Replay Temporary Workflows

src/dbos-executor.ts, src/dbos-runtime/debug.ts, src/debugger/debug_workflow.ts, src/system_database.ts
This PR uses a non-public `dbos_system` as the system DB schema in debug mode. Because the provenance exporter will export all system tables into the `dbos_system` schema in the provenance database.
This PR also updates the debug CLI to work with the debug proxy.
=> System Schema in Debug Mode

src/dbos-runtime/debug.ts
To work correctly with the proxy, now we put all tables under the `dbos` schema in the provenance DB, and we use the `userDB_prov` as the corresponding provenance DB name.
=> Update Debug Mode DB Schema and Name

src/debugger/debug_workflow.ts, tests/testing/debugger.test.ts
This PR solves a minor issue for the debug mode: If a function returns nothing, we record `null` in the database (there's no good way to serialize undefined to a valid JSON string). So when we get the recorded output, we would get `null` instead of `undefined`. Therefore, the debugger would incorrectly print out an error message when it compares `undefined` to `null` when the function returns nothing.
This PR updates the debug mode code to handle the `undefined` return value.
=> Fix Debug Mode Output Check

src/dbos-executor.ts, src/user_database.ts, tests/testing/debug_typeorm.test.ts
This PR fixes a bug where TypeORM datasource wasn't initialized under debug mode.
Also add a test for TypeORM in debug mode.
=> Fix Debug Mode TypeORM Init

src/staticAnalysis/TypeParser.ts, tests/dbos-runtime/openapi.test.ts
Detect the `import * as dbos from '@dbos-inc/dbos-sdk  construct'` for putting decorators in a namespace.
(The name `dbos` is not important.)
=> Support NamespaceImport in OpenApi gen

src/telemetry/collector.ts
Per our slack exchange with @maxdml , reduce the sleep wait time to 100ms and, every cycle, send all the data that has accumulated in the queue. Thus there is no "max message size" and we send everything we have to avoid delays and a growing RAM footprint.
I tested this change by re-running test_load and verifying that there are exactly 10,000 unique traces in the monitoring DB as soon as the test finishes. I'm considering modifying that test to check that. Requires a companion PR on the dbos-cloud side that will ensure that Zazu and otel-pg-exporter only use one postgres connection. 
Ran all the other integration tests too.
=> Send Telemetry Data Faster

src/testing/testing_runtime.ts, tests/testing/testing_runtime.test.ts
Previously, we always drop the system DB when we create a new testing runtime. However, sometimes we don't want to drop it.
For example, if I want to run multiple concurrent testing runtimes, we may not want to drop and re-create the system DB from every process.
Another example is the debug proxy test may want to keep system DB data across test runs, so we can have full provenance information.
=> Provide an option for the testing runtime to keep the systemDB

README.md
The new link is permanent and should never expire
=> Fix Discord Link

src/dbos-executor.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts, src/workflow.ts, tests/concurrency.test.ts, tests/dbos.test.ts, tests/foundationdb/foundationdb.test.ts, tests/httpServer/server.test.ts, tests/oaoo.test.ts
This PR groups individual async writes into larger insert batches into Postgres, reducing the number of round trips to the database as well as improving efficiency. Specifically, this PR groups async writes of:
- Workflow inputs for temporary workflows
- Workflow final result/status
- Workflow unflushed and buffered transaction outputs
We can tune the batch size later and implement batching for FDB as well.
=> Optimize Async Writes

src/cloud-cli/applications/deploy-app-code.ts, src/cloud-cli/userdb.ts
On a warm deploy container, not copying over `dist/` and `node_modules/` results in +/- 5s speedup:
[+] Building 15.0s (14/14) FINISHED                                    docker:default
vs
[+] Building 20.9s (15/15) FINISHED                                    docker:default
This pr also hide PGPASSWORD from the logs during migration.
=> .dockerignore for deploy + createdb security fix

src/cloud-cli/cli.ts, src/cloud-cli/userdb.ts, src/system_database.ts
This PR adds system DB and tables creation in userDB migration. So we can simply run `npx dbos-cloud userdb migrate` to create both user and system tables.
=> Create DBOS system DB and tables in cloud userdb migration

dbos-config.schema.json, dbos-test-config.yaml, examples/hello/dbos-config.yaml, src/cloud-cli/userdb.ts, src/dbos-runtime/config.ts, tests/dbos-runtime/runtime.test.ts, tests/helpers.ts
This PR removes the configurable `system_database` parameter from dbos config file.
Instead, we always set the system DB name to `<userdb>_dbos_sys`. We will enforce a similar rule for the provenance DB.
This way, we can easily export all user and system provenance data for an app, and support multiple logical user DBs/apps on the same physical DB (e.g., RDS). Otherwise, if all applications share the same system DB (previously `dbos_systemdb`), it'd be very difficult to export provenance data to each app's provenance DB.
=> Unique System DB Name Per App

examples/hello/dbos-config.yaml, schemas/system_db_schema.ts, src/cloud-cli/userdb.ts, src/dbos-executor.ts, src/dbos-runtime/debug.ts, src/system_database.ts
Previously, we put all system tables under the `public` schema in the system DB. This PR moves all tables under the `dbos` schema.
This change will make it much easier to export provenance data by leveraging Postgres logical replication, because PG doesn't support exporting tables to a different schema.
=> Move system DB tables to dbos schema

src/cloud-cli/applications/deploy-app-code.ts, src/cloud-cli/cli.ts
This PR adds a `--no-docker` flag to cloud deploy, which is useful for testing.
=> Deploy Flag: --no-docker

migrations/20240124015239_status_timestamp.js, src/dbos-executor.ts, src/dbos-runtime/runtime.ts, src/httpServer/handler.ts, src/httpServer/server.ts, src/index.ts, src/system_database.ts, src/telemetry/logs.ts, src/telemetry/traces.ts, src/testing/testing_runtime.ts, tests/foundationdb/fdb_recovery.test.ts, tests/recovery.test.ts
- Add `created_at` and `updated_at` columns to `workflow_status`
- Completely remove recovery headers, rely on the `DBOS__VMID` environment variable instead.
- Move the admin API to a separate port so it can't be triggered accidentally/maliciously by normal requests.
=> SDK Improvements

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/list-apps.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/applications/types.ts, packages/dbos-cloud/applications/update-app.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/userdb.ts
- Substitute environment variables in deploy
- Recognize `backing-up` as an available RDS instance status
- All query commands (`list`, `userdb status`) now pretty-print by default and optionally return JSON.
- Remove `MaxVMs` from the interface completely--we're serverless!
=> CLI Improvements

packages/dbos-cloud/applications/delete-app.ts, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/applications/list-apps.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/register.ts, packages/dbos-cloud/userdb.ts
Update the cloud CLI to better handle API errors, specifically printing a request ID. This ID will be useful for debugging.
Register an application:
Delete an application:
Deploying an application:
Retrieving application logs:
Registering a user:
=> Handle api errors

.npmignore, package-lock.json, packages/communicator-bcrypt/package.json, packages/communicator-datetime/package.json, packages/communicator-random/package.json
`packages` should not be in the SDK npm package
The communicator libraries should not have `dbos-sdk` as a direct dependency, but rather a peer dependency.
=> Change package list and dependencies

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/migrate.ts, src/telemetry/collector.ts, src/telemetry/exporters.ts, src/telemetry/logs.ts, src/telemetry/traces.ts
1. Changed the schema migration path to send logs to otel-exporter if available, taking care to flush the logger on exit.
2. Fixed a timing issue: otel-exporter's export() method used a callback to notify when sent. Not waiting for the callback in a very short lived command (like a failed migration) would cause telemetry data to never get sent. Changed our calls to export to wait for the callback.
3. Increased the resolution of exported timestamps.
4. NIT: made logger.destroy() to call otel-collector.destroy() for just a bit more syntax clarity.
=> Otel-log schema migrations, a couple bug fixes

packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/cli.ts
Send it to the cloud side and retrieve what comes back. Getting back an empty log is no longer an error.
=> Support the --last parameter

migrations/20240201213211_replica_identity.js
This PR adds a new column `message_uuid` as the primary key to the `dbos.notifications` table, which fixes the logical replication issue (`cannot delete from table \"notifications\" because it does not have a replica identity and publishes deletes`).
=> Add primary key to dbos.notifications

migrations/20240205223925_foreign_keys.js, schemas/user_db_schema.ts, src/dbos-executor.ts, src/dbos-runtime/migrate.ts, src/error.ts, src/system_database.ts, src/user_database.ts, src/workflow.ts, tests/dbos.test.ts, tests/oaoo.test.ts
This PR adds foreign key constraints on DBOS system tables, making the `workflow_staus.workflow_uuid` column as the core reference column for all other tables, and configures cascading updates and deletes so we can later correctly garbage collect these tables.
In addition, this PR changes behavior of the following operations:
- When we initialize workflow status, we now must synchronously set the workflow's status to PENDING and record workflow inputs for all non temp-transaction workflows. We have to do it for all types of workflows because `operation_outputs` table has a foreign key constraint on `workflow_status` table. We must ensure the workflow status exists before we record any operation output.
- For temp-transaction workflows, we must buffer inputs after workflow status is …
=> Foreign Key Constraints for System Tables

migrations/20240207192338_executor_id_index.js, src/dbos-executor.ts, tests/recovery.test.ts
This PR adds an `executor_id` index to the workflow_status table, and also skips workflow recovery if `DBOS__VMID` env variable is set.
Context: select queries on workflow_status became too slow without an index, and local workflow recovery is unnecessary if we run SDK in a FC VM.
=> Emergency Fix for Workflow Status

src/dbos-executor.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts
This PR fixes an issue where potentially multiple concurrent function invocations can export system status and input buffers at the same time (e.g., buffer took a long time to flush, but the background thread invokes flush buffer functions every 1 second), so the race condition can cause foreign key violations on the workflow inputs table.
The fix is to add a "lock" (`isFlushingBuffers`) to prevent launching multiple exporters.
We also consolidate flushing workflow status and inputs into a single system DB interface function, so we always flush workflow status buffer first.
=> Only One Can Flush Buffers

examples/hello/package-lock.json, packages/dbos-cloud/package.json, packages/dbos-openapi/package.json
This is supposed to be OK:
1. Within package.json, things are executed by node and it knows what to do without execute bit being set
2. `npm` will set the +x on things it installs that are listed in the `bin` section.  On Windows, its strategy is to create `.cmd` wrappers.
The exception is if someone wants to run cli.js directly from the shell (which only works on Unix-like shells anyway).  Then you need to change the invocation to call `node`.  If we have places that are doing that in the cloud deployment or within the firecracker vm, we will have to adjust.
I tried the OpenAPI command use of cli.js locally and it was fine.  Same for cloud command from within dev env shell, but didn't try execution within the cloud proper.
=> Remove chmod

examples/hello/dbos-config.yaml, examples/hello/package-lock.json, examples/hello/start_postgres_docker.sh, src/dbos-runtime/init.ts, src/dbos-runtime/migrate.ts, tests/dbos-runtime/runtime.test.ts
- Remove `createdb` dependency from `migrate`
- `migrate` now takes in a full shell command and runs it instead of trying to guess prefixes
- Improve `init` output
- Fix timing bug in `start_postgres_docker.sh`
=> Improve Init and Migrations

packages/dbos-cloud/applications/delete-app.ts, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/get-app-info.ts, packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/applications/list-apps.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/applications/update-app.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/register.ts
- Update Cloud CLI command names.  `dbos-cloud applications` now aliases to `application`, `app`, and `apps`.  `dbos-cloud userdb` is now `dbos-cloud database` with an alias to `databases`. 
- Consistently refer to physical database instances as "Postgres database instances" and individual databases on those instances as "application databases". Change the verbs for database instance management from "create" and "delete" to "provision" and "destroy" to reinforce this.
- Return an error if registering a user other than the logged-in user.
- Add a `logout` command.
- Return an error if running application commands outside of an application root directory.
=> Update Cloud CLI

.github/workflows/artifact.yml, .github/workflows/on_pr.yml, .github/workflows/publish_npm.yml, .github/workflows/test.yml
* Update deprecated action versions (checkout, setup-node, nbgv)
* update artifact workflow to build/pack/publish *ALL* packages
> Note, `pack` is used to build compressed tarballs of each package and attach them as an build run artifact. `publish` pushes the built packages to DBOS's GitHub package feed
=> update GitHub actions

src/debugger/debug_workflow.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts, src/workflow.ts, tests/oaoo.test.ts
This PR implements a `sleep(durationSec)` method in workflow context.
We guarantee OAOO sleep by recording the end time in the database during the first invocation of the sleep function, and only sleep until then. This way, we will never oversleep!
=> Implement sleep in Workflow Context

examples/hello/migrations/20240212161006_create_dbos_hello_tables.js, src/dbos-executor.ts, src/httpServer/handler.ts, src/workflow.ts
- Make handler span operation_uuid = requestID
- Fix traceID propagation from handler to workflow contexts
- Remove unused example/hello column
Trace ID match:
=> Fix handler tracing

src/workflow.ts, tests/dbos.test.ts, tests/failures.test.ts, tests/foundationdb/foundationdb.test.ts, tests/httpServer/classdec.test.ts
This PR fixes:
- Communicators are not sleeping long enough. Sleep method takes in milliseconds but we pass in seconds. Fixed the test so we can make sure communicators are getting enough sleep!
- Cap the maximum retry interval for both communicators (1 hour) and transactions (2 seconds). So our exponential backoff will not explode to infinity.
- Replace the deprecated `toThrowError` with the new recommended `toThrow` in our tests.
=> Fix Retry Interval

examples/hello/migrations/20240212161006_create_dbos_hello_tables.js
Add a new `dbos_greetings` table for the programming quickstart. This table does not have a primary key to enhance beginner experience.
=> split the dbos_greetings table from dbos_hello

package-lock.json, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/package.json
Zip the deploy package locally using native JS libraries instead of using `execSync("zip...")`.  Eliminates the zip dependency and makes behavior more predictable.
=> No Zip Deploy

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/debug.ts, src/dbos-runtime/runtime.ts, src/error.ts
This PR fixes the uncaught errors from the debug mode CLI, and also improves the user experience:
- `proxy` is no longer a required option. By default we run the proxy at `localhost:2345`. The only required argument is a workflow UUID.
- Capture errors from debug mode and print them out. Especially, if we get an `ECONNREFUSED` error, we prompt a hint `Is DBOS time-travel debug proxy running at ${proxy}`
- No longer need to set the database name in debug mode because the proxy is only connected to one database.
- Provide better error messages for uncompiled apps or for unrecognized operations in debug mode/runtime, adding hints for developers.
- Also bypass database password check if in debug mode, because we don't have auth between local debug proxy.
=> Better error handling for debug mode CLI

packages/dbos-cloud/applications/delete-app.ts, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/get-app-info.ts, packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/applications/update-app.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, src/telemetry/traces.ts
This PR adds an optional application name argument to `dbos-cloud app status` and `delete` commands. This way, users can delete or view their application status outside of an app folder, making it easier to install the CLI globally and use it anywhere.
Another issue this PR fixes is the incorrect startTime in traces. We use hrTime() to avoid the incorrect adjustment from opentelemetry.
=> Global App Delete/Status Commands + Timestamp Issue

examples/hello/.vscode/extensions.json, examples/hello/.vscode/launch.json, examples/hello/.vscode/tasks.json
Adds VS Code files to examples/hello so new projects are configured to use the TT Debugger extension.
[tasks.json](https://code.visualstudio.com/docs/editor/tasks) contains a single task to invoke the npm `build` script
[launch.json](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) contains a single debug configuration  configured to use `dbos-ttdbg.get-proxy-url` and `dbos-ttdbg.pick-workflow-id` commands and to invoke the `npm: build` task before debugging
[extensions.json](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) prompts the user to install our extension when they open a DBOS project in VSCode
=> Add vscode files to template

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/register.ts
Applications are now hosted at `username-appname.cloud.dbos.dev` instead of `cloud.dbos.dev/apps/username/appname`.  We make this change for two reasons:
1. So relative paths are the same locally as in DBOS Cloud.
2. So users have an easier time configuring DNS for their application.
For this to work, usernames can no longer contain dashes.
=> Improve Application Hosting 

.vscode/launch.json, src/debugger/debug_workflow.ts
Currently, the debug workflow context premptively throws if a transaction function has an error saved in the tx output table. This PR changes the `checkExecution` function to return rather than throw the error originally thrown. Execution then continues, allowing the developer to debug the tx function that originally threw an error. After the tx function completes, the debug context throws the originally recorded error.
The debug context also logs a warning to the console indicating the original execution threw an error.
=> Debug Failing Transaction Functions

.npmignore, examples/hello/tsconfig.json, package-lock.json, packages/communicator-bcrypt/tsconfig.json, packages/communicator-datetime/tsconfig.json, packages/communicator-random/tsconfig.json, packages/dbos-cloud/.npmignore, packages/dbos-cloud/applications/delete-app.ts, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/get-app-info.ts, packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/applications/index.ts, packages/dbos-cloud/applications/list-apps.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/applications/update-app.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/dashboards.ts, packages/dbos-cloud/login.ts, packages/dbos-cloud/package.json, packages/dbos-cloud/register.ts, packages/dbos-cloud/tsconfig.json, packages/dbos-cloud/userdb.ts, packages/dbos-openapi/tsconfig.json, tsconfig.json
- Emit `Node16` modules, as recommended by the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#im-writing-a-library).
- Transition the cloud CLI to ESM as several packages we'd like to use require it. No compatibility issues as the cloud CLI and SDK, by design, do not depend on each other.
- Add code to automatically detect when an application has an old version of the cloud CLI installed and recommend an upgrade.
- Auto-open login links.
=> Move Cloud CLI to ESM and Add Update Notifications

.gitignore, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/cloudutils.ts
Use node calls instead of shell commands.
Use libraries to build paths in a portable manner.
=> Changes to support Windows

src/dbos-runtime/config.ts, src/dbos-runtime/migrate.ts
This PR streamlines the use of SSL for database connections.  For more details on Postgres SSL modes, see: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION
- If an SSL certificate  is provided, connect to Postgres using SSL/TLS and verify the server certificate.
- If an SSL certificate is not provided, connect to Postgres using SSL/TLS.
- If an SSL certificate is not provided and the database hostname is `localhost`, do not use SSL/TLS. This is to support Dockerized Postgres, which does not support SSL connectinos.
=> Update SSL Configuration

examples/hello/README.md, examples/hello/start_postgres_docker.bat, examples/hello/start_postgres_docker.sh
Create a `.bat` version of the script starting a local Postgres docker, allowing a Windows user to run the entire quickstart natively without WSL.
=> Windows Quickstart

.github/workflows/test.yml, src/dbos-runtime/runtime.ts
In ESM, modules must be imported [as URLs](https://github.com/dbos-inc/dbos-ts/pull/352). This is enforced more strictly on Windows. Thus, we now import `operations.js` as a file URL.
=> Windows Fix

src/dbos-runtime/runtime.ts
In ESM, modules must be imported [as
URLs](https://github.com/dbos-inc/dbos-ts/pull/352). This is enforced more strictly on Windows. Thus, we now import `operations.js` as a file URL.
=> Windows Fix (#352)

.github/workflows/test.yml, src/httpServer/middleware.ts, src/httpServer/server.ts, src/index.ts, tests/httpServer/server.test.ts
PR adding support for custom body parsers through the `@KoaBodyParser` class decorator. If set, this overrides the default body parser for all endpoints in its class. 
Example:
```javascript
@KoaBodyParser(bodyParser({
extendTypes: {
json: ["application/json", "application/custom-content-type"],
},
encoding: "utf-8"
}))
class TestEndpoints {
...
}
```
Addresses issue https://github.com/dbos-inc/dbos-ts/issues/350
=> Custom Body Parsers

src/workflow.ts
This PR fixes an issue where `endSpan` is called multiple times incorrectly when a transaction/communicator retries.
Instead, we call `addEvent` to mark the retry event in the function context's trace span.
=> Fix transaction/communicator endSpan

package-lock.json, packages/create/cli.ts, packages/create/package.json
There were a lot of things wrong with `npm create` in the prior version.  But I didn't know this, because `npm create` doesn't work against a local package, much as that is sometimes claimed.
Fixes:
*If no command line arguments, do interactive
*If command line arguments, do what they say
*If extraneous options, because the user didn't realize `npm create` butchers your command unless you put `--`, throw an error.
=> Interactive, or command line options

examples/hello/package-lock.json, jest.config.js, package.json, packages/create/.npmignore, packages/create/init.ts
- Fix an issue where `create` would fail if `../../../..` wasn't in the filesystem (for example, if running from `/tmp`).
- Set `.npmignore` for create so all template files are included (`tsconfig.json` was excluded before)
- Alias the `dbos-sdk` command to `dbos`.
=> Fixes to Create

package-lock.json, package.json, packages/create/templates/hello/package-lock.json, packages/dbos-openapi/package.json, src/system_database.ts, src/user_database.ts
Rebuilding package-lock and upgrading to latest failed, because of:
TSC version difference, locked on 5.3.3
Issues with our PG queries in user and system database.  Improved (a little, at least compiles, but still could be better).
=> Fix PG types and rebuild package-lock

packages/dbos-cloud/applications/delete-app.ts, packages/dbos-cloud/cli.ts
Add a `--dropdb` option so users can optionally drop the app's logical DB when they delete the app.
This option should be used with cautious.
=> Support --dropdb option when delete a cloud app

dbos-config.schema.json, src/dbos-executor.ts, src/dbos-runtime/config.ts, src/httpServer/middleware.ts, src/httpServer/server.ts, src/index.ts, tests/httpServer/cors.test.ts
I9 was trying to deploy a DBOS app with a react frontend.  Calls w/ credentials to DBOS failed for CORS objections.
This PR makes CORS optional (so you could do your own CORS middleware; as it sits the main CORS will prevent anything else from running), based on the config .yaml file.  It also allows credentials by default, if not configured.
Includes a `@KoaCors` decorator that can override CORS policy for the class.  (Sort of like we are doing for body parser).
Once we have this PR settled, documentation will be needed.  That is being drafted now.
=> Make CORS configurable / optional

packages/dbos-cloud/cli.ts
This PR makes sure we don't print "Update Available" notification when the current version is the same as the latest version.
=> Fix update notifier

src/decorators.ts
I was debuging Transact using one of our demo apps. Because I was running Transact from the repo against a demo app w/ it's own version of Transact, it couldn't locate any of the handler endpoints. Because I was using two different copies of Transact, I ended up with two different sets of metadata key symbols:
https://github.com/dbos-inc/dbos-transact/blob/6e97e1ec0f80c2a359165a92e6f06e508531848e/src/decorators.ts#L78-L80
This PR switches these symbols from using Symbol's constructor to using [`Symbol.for`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for). 
```js
Symbol('bar') !== Symbol('bar');
Symbol.for('bar') === Symbol.for('bar');
```
=> use Symbol.for instead of Symbol ctor

src/dbos-executor.ts, src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts
This PR allows you to set environment variables in your `dbos-config.yaml` which are then set in your application before its code is initialized. This is especially useful for setting environment variables in DBOS Cloud.
=> Configurable Environment Variables

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/debug.ts, src/debugger/debug_workflow.ts, tests/helpers.ts, tests/testing/debug_typeorm.test.ts, tests/testing/debugger.test.ts
This PR removes the requirements for using a debug proxy when replaying a workflow in debug mode.
Without a proxy, we use recorded output/error for transactions instead of stepping through it, so we can support (limited) time travel even with self hosting.
For full database time travel experience, we still need a proxy to connect to DBOS Cloud.
=> Replay debug without a proxy

src/dbos-runtime/configure.ts
Hi,
Port number in string format results in error during deployment.
I was going through the quick start guide to setup the app and when I attempt to deploy the app with `npx dbos-cloud app deploy` it returned an error: 
```
2024-04-14 13:53:35 [info]: Loaded application name from package.json: first-dbos-app
2024-04-14 13:53:35 [info]: Submitting deploy request for first-dbos-app
2024-04-14 13:53:40 [error]: [023805e5-9f3f-4b00-aecb-76dbe741bbfb] Failed to deploy application first-dbos-app: configuring application: 1 error(s) decoding:
* 'database.port' expected type 'int', got unconvertible type 'string', value: '5432'.
```
One thing I did differently is I entered the value (5432) manually instead of the letting it pick the default value.
This was during the setup step:
```
npx dbos …
```
=> Typecast port to Number during configuration setup

packages/dbos-cloud/applications/deploy-app-code.ts
Deploy shouldn't warn if `PGPASSWORD` isn't set because DBOS Cloud doesn't use local `PGPASSWORD`.
=> Eliminate Spurious Warning

src/telemetry/logs.ts
Pass the desired `logLevel` configuration to `OTLPLogQueueTransport`.
Output of `npx dbos-cloud app logs` with previous/new version of Transact:
=> pass logLevel to OTLPLogQueueTransport

packages/dbos-cloud/cli.ts, packages/dbos-cloud/userdb.ts
Add a new option `--enable-timetravel` to the link DB command. If this option is set, we set up database time travel infra on DBOS Cloud for the linked Postgres.
=> BYOD Time Travel Option

.github/workflows/test.yml, dbos-config.schema.json, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/debug.ts, src/dbos-runtime/runtime.ts, tests/dbos-runtime/config.test.ts, tests/dbos-runtime/runtime.test.ts
Allow the configuration of multiple files to declare DBOS classes. The user experience is:
- Default entry point is `dist/operations.js`
- `runtimeConfig` now accepts a list of `entrypoints`
- Users can override the configuration when starting DBOS Transact with the `--entrypoints` CLI flag
- breaking changes: `--entrypoint` flag and `runtimeconfig.entrypoint` config property are removed
=> register many entrypoints

dbos-config.schema.json, packages/create/templates/hello/dbos-config.yaml, src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts
This PR allows disabling SSL/TLS for DB connections, for example for local development, through the new `ssl` configuration parameter.  For security, SSL remains on by default and is always used in DBOS Cloud.  Addresses https://github.com/dbos-inc/dbos-transact/issues/397.
=> Allow Disabling SSL for DB Connections

src/workflow.ts, tests/concurrency.test.ts
The transaction guard logic in workflow execution (introduced way back in https://github.com/dbos-inc/dbos-transact/pull/13) adds considerable complexity but doesn't improve safety in normal execution, so we removed it.
=> Remove Guards

packages/dbos-cloud/cli.ts, packages/dbos-cloud/databases/databases.ts
This PR implements a new Cloud command to restore a DB instance to a past point in time.
```
Usage: dbos-cloud database restore [options] <name>
Restore a Postgres database instance to a specified time
Arguments:
name                         database instance name
Options:
-t, --restore-time <string>  Specify the timestamp to restore from, must be in RFC3339 format. Example: 2009-09-07T23:45:00Z
-n, --target-name <string>   Specify the new database instance name
-h, --help                   display help for command
```
=> DB restore command

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/cli.ts
This PR implements a command to change the database instance to which an app is connected, redeploying the app in the process (potentially to a previous version).  This is most useful when performing database point-in-time-recovery (https://github.com/dbos-inc/dbos-transact/pull/409), to redeploy the application to the recovered database instance.
=> Change Application Database Instance

packages/create/cli.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, src/communicator.ts, src/dbos-executor.ts, src/debugger/debug_workflow.ts, src/foundationdb/fdb_system_database.ts, src/telemetry/collector.ts, src/transaction.ts, src/user_database.ts, tests/concurrency.test.ts, tests/dbos.test.ts, tests/failures.test.ts, tests/foundationdb/foundationdb.test.ts, tests/httpServer/classdec.test.ts, tests/httpServer/cors.test.ts, tests/httpServer/server.test.ts, tests/httpServer/validation.test.ts, tests/kafka/kafka.test.ts, tests/knex.test.ts, tests/oaoo.test.ts, tests/prisma.test.ts, tests/testing/debugger.test.ts, tests/typeorm.test.ts
There is more to be done towards enabling typing to as many places as possible.
Two cases draw my attention covering possibly never ending loops with // eslint-disable-next-line no-constant-condition.
At first glance both cases look like asking for a user defined retry strategy instead of a while(true) loop.
=> This PR tries to lower the usage of unnecessary disabling of linting rules

src/workflow.ts
Currently, we only see `Communicator reached maximum retries.` in the log. Should log all errors and trace events from retries.
=> Always log and record communicator error

.gitignore, packages/create/templates/hello-typeorm/.vscode/extensions.json, packages/create/templates/hello-typeorm/.vscode/launch.json, packages/create/templates/hello-typeorm/.vscode/tasks.json, packages/create/templates/hello/.vscode/extensions.json, packages/create/templates/hello/.vscode/launch.json, packages/create/templates/hello/.vscode/tasks.json
Add a `.vscode` folder to the template to provide helpful defaults to VSCode users building DBOS apps. Addresses https://github.com/dbos-inc/dbos-transact/issues/394.
=> Return VSCode Configuration to Template

src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, tests/dbos-runtime/runtime.test.ts
Allow specifying an application directory in `npx dbos start` to launch the application in that directory.
```
npx dbos start --appDir <path/to/application>
```
Deprecate the previous `--configFile` option, which had confusing semantics.  Addresses https://github.com/dbos-inc/dbos-transact/issues/399.
=> Configurable Application Directory

src/kafka/kafka.ts, tests/kafka/kafka.test.ts
This PR is a temporary workaround for https://github.com/tulios/kafkajs/pull/1558 until it gets fixed. If topic autocreation is on and you try to subscribe to a nonexistent topic, KafkaJS should retry until the topic is created. However, curently KafkaJS does not retry, so Transact will instead.
=> Kafka Retries

src/kafka/kafka.ts, tests/kafka/kafka.test.ts
kafkajs provides support for it so why not expose it?
This can be extended so as to receive an Array<string | RegExp> instead of just one.
=> Add support for subscribing to topics by regex

src/kafka/kafka.ts, tests/kafka/kafka.test.ts
This PR adds support for declaring an array of topics for a consumer.
=> KafkaConsume accept array of string or RegExp 

src/dbos-runtime/cli.ts, src/dbos-runtime/migrate.ts, src/decorators.ts, src/telemetry/index.ts, src/telemetry/logs.ts
This PR makes logging of execSync errors typed and consistent in migration.ts.
It also removes some //eslint-disable from telemetry
=> Make logging consistent in migration.ts

.eslintignore, package.json, src/dbos-executor.ts, src/decorators.ts, src/httpServer/handler.ts, src/httpServer/server.ts, src/telemetry/logs.ts, src/user_database.ts, tests/dbos-runtime/runtime.test.ts, tests/httpServer/cors.test.ts, tests/httpServer/validation.test.ts, tests/telemetry.test.ts
This PR adds the --report-unused-disable-directives which removes all unused eslint disable directives.
It also adds a .eslintignore file that excludes the `.eslintrc.cjs` file.
This is because after enabling the Microsoft eslint plugin in VSCode it  complains about [this](https://typescript-eslint.io/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file)
Many ways to solve it and I picked the easiest one.
Really why the `.cjs` extension? why not `.js` or '.json' ?
=> add the  --report-unused-disable-directives to lint script

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/get-app-logs.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/cli.ts
This is useful if we want to deploy the same code to two different apps, for example for staging vs prod deployments we can have `app-staging` vs `app-prod`.
This PR also makes it possible to retrieve logs for other apps.
=> Allow app to register/deploy under a different name

src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/debugger/debug_workflow.ts, src/httpServer/handler.ts, src/testing/testing_runtime.ts, src/workflow.ts, tests/concurrency.test.ts, tests/dbos.test.ts, tests/failures.test.ts, tests/foundationdb/fdb_oaoo.test.ts, tests/foundationdb/fdb_recovery.test.ts, tests/foundationdb/foundationdb.test.ts, tests/httpServer/classdec.test.ts, tests/httpServer/server.test.ts, tests/knex.test.ts, tests/oaoo.test.ts, tests/recovery.test.ts, tests/testing/debugger.test.ts, tests/testing/testing_runtime.test.ts
This PR introduces two new methods for invoking workflows from handlers.  For workflow bar in class Foo with argument arg:
- `ctxt.startWorkflow(Foo).bar(arg)` starts the workflow and returns its handle. This is equivalent to the current `ctxt.invoke(Foo).bar(arg)`.
- `ctxt.invokeWorkflow(Foo).bar(arg)` executes the workflow and returns its result. This is equivalent to the current `ctxt.invoke(foo).bar(arg).then((x)=>x.getResult())`.  The latter is very unintuitive and is tripping users up.
To avoid confusion, we also deprecate calling `invoke` on workflows--use one of the new methods instead.
My hope is that this makes it much clearer to users what is actually happening when a handler invokes a workflow.
=> Workflow Invocation Methods

package-lock.json, package.json, packages/communicator-bcrypt/package.json, packages/communicator-datetime/package.json, packages/communicator-random/package.json, packages/create/package.json, packages/dbos-cloud/package.json, packages/dbos-openapi/package.json
* update ts-json-schema-generator to 1.5.1
* update typescript to 5.4.5
> Note, ts-json-schema-generator moved to ESM in v2. Will need to update at least dbos-openapi to use ESM if we want to use v2 of this library
=> Update typescript and ts-json-schema-generator 

src/communicator.ts, src/dbos-executor.ts, src/dbos-runtime/runtime.ts, src/debugger/debug_workflow.ts, src/httpServer/handler.ts, src/httpServer/server.ts, src/kafka/kafka.ts, src/scheduler/scheduler.ts, src/system_database.ts, src/testing/testing_runtime.ts, src/transaction.ts, src/user_database.ts, src/workflow.ts, tests/dbos.test.ts
This reverts commit 8f1b5d4f44bb6dfb80a049693fb78f7125789451 as it included breaking API changes. It caused numerous failures on our demo applications and in our staging environment and cannot be released in its current state. The changes in that PR are good, but we need to introduce them gradually and carefully (likely in multiple smaller PRs) and verify they don't cause regressions.
=> Revert "Reduce usage of "any" (#448)"

Gruntfile.js, package-lock.json, package.json, packages/communicator-bcrypt/Gruntfile.js, packages/communicator-bcrypt/package.json, packages/communicator-datetime/Gruntfile.js, packages/communicator-datetime/package.json, packages/communicator-random/Gruntfile.js, packages/communicator-random/package.json, packages/create/Gruntfile.js, packages/create/package.json, packages/dbos-cloud/Gruntfile.js, packages/dbos-cloud/package.json, packages/dbos-openapi/Gruntfile.js, packages/dbos-openapi/package.json
we originally used grunt to set package version via nerdbank git version. However, we now do this directly with the `npm version` command in the `artifact.yml` GH Workflow so we don't need grunt anymore.
Assuming you have .NET runtime installed, you can stamp versions locally like this:
```sh
version=$(npx nbgv get-version -v NpmPackageVersion)
npm version --workspaces --include-workspace-root --no-git-tag-version "$version"
```
=> remove grunt dependencies + files

src/dbos-executor.ts, src/debugger/debug_workflow.ts, src/foundationdb/fdb_system_database.ts, src/httpServer/handler.ts, src/system_database.ts, src/testing/testing_runtime.ts, src/workflow.ts
There are numerous instances of `<T extends NonNullable<any>>` in the messaging APIs that are non-functional (`T` can still be null), shouldn't be there (several apps send a null message to indicate failure, such as in [this demo](https://github.com/dbos-inc/dbos-demo-apps/blob/main/widget-store/src/operations.ts)), and confusing. This PR removes them, making the message type `T` fully generic.
=> Fix NonNullable

packages/create/init.ts
The latest versions of some of our popular dev dependencies (`jest` and `ts-jest`) contain deprecated dependencies that print warnings when installed. For now, we suppress those warnings. Going forward, we need to:
- Upgrade to the next version of `jest` and `ts-jest` when they're released.
- Upgrade to the latest `eslint` soon. This is difficult because it completely changes how the linter is configured, so we'll have to redo our linter configuration files from scratch. (https://github.com/dbos-inc/dbos-transact/issues/458)
=> Suppress Dev Dependency Warnings

packages/create/init.ts
The latest versions of some of our popular dev dependencies (`jest` and `ts-jest`) contain deprecated dependencies that print warnings when installed. For now, we suppress those warnings. Going forward, we need to:
- Upgrade to the next version of `jest` and `ts-jest` when they're released.
- Upgrade to the latest `eslint` soon. This is difficult because it completely changes how the linter is configured, so we'll have to redo our linter configuration files from scratch.
(https://github.com/dbos-inc/dbos-transact/issues/458)
=> Suppress Dev Dependency Warnings (#477)

src/dbos-runtime/migrate.ts, src/user_database.ts
This PR fixes two issues:
- In migrate.ts, we skipped creating transaction outputs table if the schema exists. However, it's possible that the schema exists but the table doesn't. So we have to move table creation out of schema existence check.
- In both migrate.ts and user_database.ts, always check if a schema/table/index exists before running `CREATE IF NOT EXISTS` queries. The reason is that those DDL queries would hold locks and we don't want to always lock the table when we start a Transact program.
=> Check existence before create schema/table

src/dbos-executor.ts, src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts, tests/testing/debugger.test.ts
This PR fixes an issue where the undefined `PGPASSWORD` env in `dbos-config.yaml` was parsed as `null` not an empty string. This makes schema validation failed (i.e., debug mode with undefined password) because `null` is not a `string` type. The fix is to move the check for database password in `parseConfigFile` and assign the password to `"PROXY-MODE"` if not set.
Tests:
- Added a test to make sure debug mode with a proxy allows undefined `PGPASSWORD`.
- Fixed a minor issue in test where the proxy url wasn't correct and caused the logger to print `: NaN` in tests.
=> Allow proxy debug mode with undefined password

packages/create/templates/hello-prisma/generate_env.js, packages/create/templates/hello-typeorm/datasource.ts, packages/create/templates/hello/knexfile.js
Tested hello template by using current @dbos-inc/create command, updating generated knexfile.js to match the change in this PR and running `npx dbos migrate`. Still need to test typeorm and prisma templates
=> update templates to use exported parseConfigFile

packages/component-aws-s3/index.ts
`index.ts` got missed in the first version of S3.
=> S3: Missing index.ts

schemas/system_db_schema.ts, src/foundationdb/fdb_system_database.ts, src/httpServer/handler.ts, src/index.ts, src/system_database.ts, src/workflow.ts, tests/httpServer/server.test.ts, tests/workflow_management.test.ts
This PR introduces a new `getWorkflows()` method allowing users to query the statuses of their workflows. For now, this is a method of `HandlerContext`.
This method takes in the following input:
```typescript
export interface GetWorkflowsInput {
workflowName?: string; // The name of the workflow function
authenticatedUser?: string;
startTime?: string; // In RFC 3339 format
endTime?: string; // In RFC 3339 format
status?: "PENDING" | "SUCCESS" | "ERROR";
applicationVersion?: string;
}
```
It returns a list of the UUIDs of all workflows that satisfy all the constraints specified in the input.
For example, to find the UUIDs of all executions of `testWorkflow` that errored, run:
`getWorkflows({workflowName: "testWorkflow", status: StatusString.Error})`
You can then call `retrieveWorkflow` on …
=> Workflow Introspection

package.json, src/debugger/debug_workflow.ts, src/system_database.ts, src/workflow.ts, tests/dbos.test.ts, tests/workflow_management.test.ts
- Make it possible to retrieve a workflow's input from its workflow handle.
- Add a `limit` argument to `getWorkflows()`
=> Retrieve Workflow Inputs

migrations/20240621000000_workflow_tries.js, src/dbos-executor.ts, src/error.ts, src/system_database.ts, src/workflow.ts, tests/recovery.test.ts
This PR implements a [dead letter queue](https://en.wikipedia.org/wiki/Dead_letter_queue) for workflows. If a workflow execution is recovered more than N times (50 by default, configurable in `WorkflowConfig`), it is placed in the dead letter queue and no further attempts will be made to recover it. A list of all workflows in the dead letter queue can be retrieved with `getWorkflows()`.
The goal of this change is to reduce the damage caused by buggy workflows that crash the execution environment. Without a dead letter queue, these will be retried indefinitely, wasting resources and disrupting other works. With this change, they are retried a maximum number of times then placed in the DLQ for manual investigation and restart.
=> Dead Letter Queue

package.json, src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/workflow_management.ts, src/foundationdb/fdb_system_database.ts, src/system_database.ts, src/workflow.ts, tests/workflow_management.test.ts
This PR adds a command-line interface for workflow management. There are five new commands:
- `npx dbos workflow list`: List workflows run by your application. Takes in parameters to filter on time, status, user, etc.
- `npx dbos workflow get <uuid>`: Retrieve the status of a workflow.
- `npx dbos workflow cancel <uuid>`: Cancel a workflow so it is no longer automatically retried or restarted . Active executions are not halted and the workflow can still be manually retried or restarted.
- `npx dbos workflow resume<uuid>`: Resume a workflow from the last step it executed, keeping its UUID.
- `npx dbos workflow restart<uuid>`: Resubmit a workflow, restarting it from the beginning with the same arguments but a new UUID.
=> Workflow Management CLI

src/system_database.ts, tests/configuredinstances.test.ts, tests/prisma.test.ts, tests/testing/debugger.test.ts
This PR fixes an issue where `class_name` and `config_name` were not correctly captured for transactions.
Updated tests for both normal classes and configured classes.
=> Correctly capture class name and config name

src/dbos-executor.ts
I noticed an exception being thrown when loading classes fail. See:
When initializing the dbos runtime, we first construct the class, then load the applications classes through entry points, then call `init()`. Failure to load the class results in an undefined user database, which in turn results in an exception being throw. The exception pollutes the output and degrades UX.
=> check userdb is defined before calling destroy

src/workflow.ts, tests/oaoo.test.ts
Child workflow keys - was already basically implemented, but somehow not exposed / tested.
=> Allow invokeWorkflow to specify OAOO key for child

packages/dbos-cloud/applications/deploy-app-code.ts
As the title says. Convenient.
=> display app archive size, in bytes, during deploy, in verbose mode

packages/dbos-cloud/applications/deploy-app-code.ts
Using JSZip:
- Capture each files permissions when adding them to the archive
- Specify the platform (UNIX)
=> preserve file permissions when creating the app archive

packages/dbos-cloud/databases/databases.ts
[`npx dbos-cloud db connect`](https://docs.dbos.dev/api-reference/cloud-cli#npx-dbos-cloud-db-connect) overwrites the `dbos-config.yaml` configuration file, so it should create a backup of the original before doing so.
=> Create a Backup Configuration File in db connect

src/dbos-runtime/debug.ts, src/dbos-runtime/runtime.ts, src/dbos-runtime/workflow_management.ts
This PR fixes an issue where the debug mode runtime didn't properly register all classes.
Also simplify the class registration logic everywhere -- we don't need to pass classes into `dbosExec.init()` anymore, because this `init()` function already registers all classes if no class specified.
=> Fix class registration

src/dbos-executor.ts
The `init()` call for a PG user database client can return aggregate errors. If we don't handle them properly, the returned error is missing a message:
This PR adds a type check to parse `AggregateError`:
=> handle AggregateError during DBOS executor init

src/system_database.ts, tests/workflow_management.test.ts
This PR handles the system DB migration failure correctly so old app versions can still run on the new system DB schema. It is safe because we try not to make any backward incompatible changes.
Specifically, an error may happen if the old version detects a new migration in `knex_migrations` table but doesn't have the new migration file. With this PR, old versions can correctly proceed to run. This is important when we want to recover pending workflows under old app versions.
=> Handle system DB migration failure for forward compatibility

packages/dbos-cloud/cli.ts
Our cloud CLI uses ESM. Due to some recent updates in our dependencies, we start seeing a warning like:
```
(node:85015) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
at emitExperimentalWarning (node:internal/util:275:11)
at ModuleLoader.jsonStrategy (node:internal/modules/esm/translators:464:3)
at callTranslator (node:internal/modules/esm/loader:285:14)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
```
This PR suppresses this experimental warning.
=> Suppress cloud CLI experimental warning

packages/dbos-cloud/cli.ts
According to https://github.com/nodejs/node/issues/30810
We need to use `#!/usr/bin/env -S node --no-warnings=ExperimentalWarning`  on Linux. Otherwise it hangs. This flag also works on other OS environments.
=> Fix executable

src/scheduler/scheduler.ts, tests/scheduler/scheduler.test.ts
This PR solves a bug where the runtime will hang as long as the longest scheduled interval (like a few hours). The solution is to properly clear the scheduler timeout.
Added a test to make sure the test can return within a reasonable time.
=> Clear scheduler timeout properly

package-lock.json, packages/create/init.ts, packages/create/package.json
This PR improves DX by updating the `app_db_name` field to the app name during `npx create`. This way, it prevents users from mistakenly using the same database for different apps.
Since Postgres database names "must begin with a letter or an underscore ( _ ). Subsequent characters in an identifier or key word can be letters, underscores, digits ( 0 - 9 )", we have to handle app names that don't follow this rule:
- Substitue dashes "-" to underscores "_".
- Append an underscore if the app name starts with a digit.
=> Default app_db_name to app name

src/debugger/debug_workflow.ts, src/system_database.ts, src/workflow.ts, tests/oaoo.test.ts
This PR aims to address #451.
I only implemented durable timeout in the `recv` method for now so as to get your feedback before implementing
the functionality in the `getEvent` method.
=> implement durable timeout in system database recv

tests/oaoo.test.ts
We can directly set the workflow UUID for the child workflow. No longer need to hard code the child UUID.
=> Fix OAOO getEvent test

src/debugger/debug_workflow.ts, src/system_database.ts, src/workflow.ts, tests/oaoo.test.ts
This PR aims to add durable timeout to the `getEvent` method of system_database
=> Implement durable timeout in workflow getEvent

src/communicator.ts, src/dbos-executor.ts, src/httpServer/server.ts, src/scheduler/scheduler.ts, src/workflow.ts, tests/failures.test.ts
This fixes unintuitive behaviors that sparked user complaints:
1. Scheduled workflows now default to `ExactlyOncePerIntervalWhenActive`. This means that if an executor is started after being deactivated for a long time, it does not try to "catch up" on past scheduled workflows. This is paired with a related bugfix (https://github.com/dbos-inc/dbos-transact/pull/577)  so this behavior and flag now work as intended.
2. Communicator retries now clearly emit error messages that explain what's going on, so they're no longer swallowed.
3. Fixed an issue where workflow errors were logged twice: once by the workflow and once by the handler.
=> Fix Unintuitive Behavior

.github/workflows/publish_npm.yml
Fix an issue in our Github action where the publish didn't build packages correctly.
Root cause was that I modified the dbos-sdk in package-lock.json to be:
```
"node_modules/@dbos-inc/dbos-sdk": {
"resolved": "",
"link": true
},
```
So we must build the root package first.
=> Fix publish action

src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/migrate.ts, tests/dbos-runtime/config.test.ts
Make sure Transact enforces the same DB name validation rules as in DBOS Cloud.
=> Validate DB name when parsing dbos config

src/dbos-executor.ts, tests/drizzle.test.ts, tests/typeorm.test.ts
Separate TypeORM and Drizzle entities to fix a bug where a blank `@ORMEntities` decorator would disallow registering further entities.
=> Fix TypeORM Entities

src/dbos-executor.ts, tests/drizzle.test.ts, tests/typeorm.test.ts
Separate TypeORM and Drizzle entities to fix a bug where a blank `@ORMEntities` decorator would disallow registering further entities.
=> Fix TypeORM Entities (#596)

src/httpServer/server.ts
When taking a boolean as input to an API endpoint, DBOS was incorrectly throwing:
`[error]: Missing required argument decision of <endpoint method>`
When `false` was the input.
=> Fixed issue where API methods couldn't accept false as an input

package-lock.json, packages/create/templates/hello/src/operations.ts, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/package.json
This PR aims to reduce DBOS Cloud app deploy to a single command.
- First, check if the app is registered or not. If so, proceed to the normal deploy (this PR is fully backward compatible).
- If the app is not registered, then select a database server to use for this app.
- List all database servers for the current user.
- If the user doesn't have any database, then prompt to provision one.
- If the user has more than one database servers, then prompt to choose one.
- If the user has only one database server, then use it.
- Finally, register the app and deploy normally.
Discussion:
- Currently, it uses a default PG role name `dbosapp_default` and a generated password. Do we want user input for those?
=> Simplify dbos-cloud app deploy

packages/dbos-cloud/cli.ts
The warning is no longer appearing and the shebang is broken on Windows.
=> Fix broken shebang on Windows

packages/dbos-cloud/cli.ts
The warning is no longer appearing and the shebang is broken on Windows.
=> Fix broken shebang on Windows (#600)

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/configutils.ts
Add support for specifying `-d, --database <string>` and `--enable-timetravel` options in `npx dbos-cloud app deploy`.
Those two options are only effective during the initial deployment. Subsequent changes to a deployed app won't have any effect.
=> App deploy supports all options from register

packages/dbos-cloud/applications/deploy-app-code.ts
For backward compatibility, don't check the app's DB name if it doesn't exist.
=> Fix deploy app_db_name check

packages/dbos-cloud/applications/deploy-app-code.ts
The venv should not be shipped with the application code.
=> Don't Bundle Virtual Environments When Deploying Python Apps

src/scheduler/scheduler.ts, tests/scheduler/scheduler.test.ts
Fix issue https://github.com/dbos-inc/dbos-transact/issues/613
The recorded name is always `<className>.<methodName>` now.
=> Record scheduled workflow name with its class name

package-lock.json, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/users/register.ts
As the Cloud CLI is now cross-language, handling both TypeScript and Python apps, we recommend installing it globally and accessing it as `dbos-cloud` instead of `npx dbos-cloud`.
=> Recommend Globally Installing Cloud CLI

packages/create/templates/hello-drizzle/src/operations.ts, packages/create/templates/hello-prisma/src/operations.ts, packages/create/templates/hello-typeorm/src/operations.ts, packages/create/templates/hello/src/operations.ts, packages/dbos-openapi/tests/openapi.test.ts
Mostly copying over what P&Q did for the Python app but with more direct links to send the user to the right docs in each case.
=> CSS facelift for the Hello app and the schema-specific templates

packages/aws-config/README.md, packages/aws-config/index.ts, packages/communicator-email-ses/index.ts, packages/component-aws-s3/src/s3_utils.ts, packages/dbos-sqs/README.md, packages/dbos-sqs/index.ts, packages/dbos-sqs/sqs-test-dbos-config.yaml, packages/dbos-sqs/sqs.test.ts
Add endpoints for SES, SQS, and S3 libraries.
=> AWS service endpoints

src/workflow.ts
Remove unneeded parameterization of new spans with executor IDs. Executor ID is statically set in the OTLP queue.
=> executorID is set statically in OTLPLogQueueTransport

src/dbos-executor.ts, src/dbos-runtime/runtime.ts, src/index.ts, src/testing/testing_runtime.ts, tests/httpServer/classdec.test.ts
Export a global logger, so that your middleware can do something like this:
```
// Logging middleware
const logAllRequests = () => {
return async (ctx: Koa.Context, next: Koa.Next) => {
const start = Date.now();
// Log the request method and URL
DBOS.globalLogger?.info(`[Request] ${ctx.method} ${ctx.url}`);
let ok = false;
try {
await next();
ok = true;
}
finally {
const ms = Date.now() - start;
if (ok) {
// Log the response status and time taken
DBOS.globalLogger?.info(`[Response] ${ctx.method} ${ctx.url} - ${ctx.status} - ${ms}ms`);
}
else {
// Log error response
DBOS.globalLogger?.warn(`[Exception] ${ctx.method} ${ctx.url} - ${ctx.status} - ${ms}ms`);
}
}
};
};
@KoaGlobalMiddleware(logAllRequests)
```
=> Make it easier to get the global logger

packages/communicator-bcrypt/README.md, packages/communicator-bcrypt/index.ts, packages/communicator-datetime/README.md, packages/communicator-datetime/index.ts, packages/communicator-email-ses/index.ts, packages/communicator-random/README.md, packages/communicator-random/index.ts, packages/dbos-compiler/compiler.ts, packages/dbos-sqs/index.ts, src/communicator.ts, src/dbos-executor.ts, src/debugger/debug_workflow.ts, src/decorators.ts, src/eventreceiver.ts, src/httpServer/handler.ts, src/httpServer/server.ts, src/index.ts, src/step.ts, src/testing/testing_runtime.ts, src/workflow.ts, tests/concurrency.test.ts, tests/configuredinstances.test.ts, tests/dbos.test.ts, tests/failures.test.ts, tests/foundationdb/foundationdb.test.ts, tests/httpServer/server.test.ts, tests/oaoo.test.ts, tests/testing/debugger.test.ts, tests/testing/debugger_configuredinst.test.ts
This is a "step" in the journey of calling things "step" rather than "communicator" across TS and Python.
Allow @Step, StepContext, etc., while keeping @Communicator, CommunicatorContext, etc., working.
Also add aliases in some of the communicator libraries.
We would be able to do a lot of doc and demo work with this change, then wrestle down the rest.
=> Allow use of "Step" instead of "Communicator"

src/error.ts, src/user_database.ts, src/workflow.ts, tests/dbos.test.ts
If a `@Transaction` method invokes a user-authored stored procedure that raises an exception, the db transaction is aborted even if the exception is caught in the `@Transaction` method. If the exception is caught and handled in the `@transaction` method, DBOS will fail when it attempts to write the `@Transaction` method return value to the `transaction_outputs` table because the associated db transaction has been aborted. This PR creates a DBOS specific error to throw in this situation. 
Fixes #626
=> DBOSFailedSqlTransactionError

dbos-config.schema.json, src/dbos-runtime/config.ts, src/dbos-runtime/runtime.ts, src/httpServer/server.ts, tests/dbos-runtime/config.test.ts, tests/dbos-runtime/runtime.test.ts
Now you can specify the admin_port field under runtimeConfig in the dbos-config.yaml file.
Added a test to make sure we can specify a different port.
=> Configurable admin server port

dbos-config.schema.json, packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/types.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/cloudutils.ts, packages/dbos-cloud/configutils.ts, packages/dbos-cloud/databases/databases.ts, src/dbos-runtime/config.ts, src/dbos-runtime/migrate.ts, tests/dbos-runtime/config.test.ts
Add support for using a DBOS Cloud Postgres server for local development.
=> Use Cloud Database Locally

packages/dbos-cloud/applications/deploy-app-code.ts, packages/dbos-cloud/applications/index.ts, packages/dbos-cloud/applications/register-app.ts, packages/dbos-cloud/applications/types.ts, packages/dbos-cloud/applications/update-app.ts, packages/dbos-cloud/cli.ts
TODO:
- Look into import error
=> allow the configuration of executors memory during deploy

migrations/20241009150000_event_dispatch_kv.js, schemas/system_db_schema.ts, src/dbos-executor.ts, src/dbos-runtime/runtime.ts, src/decorators.ts, src/eventreceiver.ts, src/foundationdb/fdb_system_database.ts, src/index.ts, src/scheduler/scheduler.ts, src/system_database.ts, src/testing/testing_runtime.ts, tests/eventreceiver.test.ts
Added the following things to Event Receiver API:
.  Ability to query app (user) DB
.  Ability to listen for notifications on app DB
.  Ability to store state in the system DB
=> Infrastructure for DB trigger event receiver

packages/dbos-cloud/applications/deploy-app-code.ts
Need to substitute env variables when checking the config file during deploy.
=> Fix env substitution bug in deploy

packages/dbos-cloud/applications/deploy-app-code.ts
Need to substitute env variables when checking the config file during deploy.
=> Fix env substitution bug in deploy (#651)

dbos-config.schema.json, packages/create/init.ts, packages/create/templates/hello-drizzle/dbos-config.yaml, packages/create/templates/hello-prisma/dbos-config.yaml, packages/create/templates/hello-typeorm/dbos-config.yaml, packages/create/templates/hello/dbos-config.yaml, packages/dbos-cloud/applications/deploy-app-code.ts, src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts, tests/dbos-runtime/runtime.test.ts
Make `app_db_name` optional and remove it from the template. If it's not specified, use the app name (suitably transformed) as `app_db_name`.
=>  Simplify Database Configuration

packages/dbos-cloud/applications/types.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/databases/databases.ts
- Attempting to reset the password of a linked database gives clearer error messages.
- `db local` works for Supabase.
=> Cloud CLI Supabase Support

packages/dbos-cloud/applications/index.ts, packages/dbos-cloud/applications/secrets.ts, packages/dbos-cloud/cli.ts
(1) npx dbos-cloud app secrets create
(2) npx dbos-cloud app secrets list
=> Secrets cli

packages/create/templates/hello-v2/src/operations.test.ts, src/dbos.ts, src/httpServer/server.ts
Start DBOS HTTP server from launch() if it makes sense to do so
Add unit tests to the create/hello-v2 package
=> HTTP Server improvements / testing

packages/dbos-cloud/applications/deploy-app-code.ts
.dbosignore files has a list of files/directories to ignore.
A minimal .gitignore
e2e test will be a PR from dbos-cloud
=> Dbosignore

.gitignore, package-lock.json, packages/dbos-cloud/applications/secrets.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/package.json
Support for importing secrets from a dotenv file. All environment variables in the file will be imported as DBOS Cloud secrets and made available as environment variables to the deployed application. Aim is to simplify environment management. Import a file with:
```shell
dbos-cloud app secrets import -d .env
```
Supported dotenv file syntax: https://dotenvx.com/docs/env-file
=> Import Secrets

package-lock.json, packages/dbos-compiler/compiler.ts, packages/dbos-compiler/tests/more-compiler.test.ts, packages/dbos-compiler/tests/test-code.ts, packages/dbos-compiler/tests/test-utility.ts, tests/proc-test/src/operations.test.ts, tests/proc-test/src/operations.ts
This PR adds support to dbos-compiler for the new v2 API (i.e. `@DBOS.workflow` decorators et. al.). This PR does *NOT* add a `@DBOS.storedProc` decorator...that will come in a separate PR
=> dbos compiler support for v2 API

src/dbos.ts
Today this way of automatically starting our server is not compatible with how we allow users to specify their own `start` command. 
Specifically, if I pass a `start` command to `runtimeConfig`, the current logic will fail and crash if there is already a server listening on our default port (3000).
We can revisit what magic we want to do about that HTTP server, in the future...
=> do not start our http server during DBOS.launch()

src/dbos.ts, tests/contextfreeapi.test.ts, tests/contextfreeinst.test.ts
Allow setting of workflow ID and queue as part of startWorkflow syntax.
Remove a couple of comments that don't mean anything any more.
=> Add parameters to startWorkflow

packages/create/templates/hello-v2/src/operations.test.ts, src/context.ts, src/dbos.ts, src/httpServer/server.ts, tests/httpserve_v2.test.ts
Way to launch HTTP in unit tests
More unit tests (outside of template)
Fix for WFID in HTTP header
Clarify `withNextWorkflowID` use of ID.
=> HTTP WFID test/fixes

package-lock.json, packages/dbos-cloud/applications/deploy-app-code.ts
Fail a deploy of a Python app if `requirements.txt` does not include `dbos`.
=> Check Requirements

packages/dbos-cloud/applications/deploy-app-code.ts
The inclusion of a `./python-version` file may cause DBOS Cloud to install packages for the wrong version. This file should be ignored in the cloud.  Thanks [@camspilly](https://github.com/camspilly) for reporting!
=> Ignore .python-version

src/dbos-executor.ts
Trying to cut down on the nuisance diffs between main and Harry's branch.
=> Whitespace

src/context.ts, src/dbos.ts, tests/contextfreeapi.test.ts, tests/v2v1apimix.test.ts
These were found during conversion of demo apps to v2:
* setAppConfig - used in unit tests (was provided by testingRuntime as setConfig)
* Calling v1 transaction/step functions using DBOS.invoke(), from outside of workflows
* Using DBOS.logger before launch
=> v2 API touchups

src/dbos.ts, src/error.ts, tests/contextfreeapi.test.ts
Based on the experience of Manoj and others - improve error messages for making calls at the wrong point in the workflow, tests for same.
=> Clear error messages for invalid WF transitions

package-lock.json, packages/create/.npmignore, packages/create/cli.ts, packages/create/github-create.ts, packages/create/init.ts, packages/create/package.json
This PR improves the `create` command:
- Provide a list of valid templates to select from.
- Support creating demo apps from their GitHub repo (currently only dbos-node-starter).
- Improving error messages by adding colors and bold fonts.
Will add more templates and clean up the templates in a separate PR.
=> Create from demo repo

packages/create/.npmignore, packages/create/init.ts, packages/dbos-cloud/applications/deploy-app-code.ts
- Include the new `dbos-nextjs-starter` in the create command.
- Fix the ignore patterns of dbosignore. Need to append `**` if the pattern ends with `/`. Otherwise, nothing in that folder can be matched.
=> Update templates and fix dbosignore

packages/create/templates/dbos-knex/dbos-config.yaml, src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts
`local_suffix` may only be true when connecting a remote database, not to `localhost`
=> Detect Invalid Config Setting

.github/workflows/publish_npm.yml, src/httpServer/middleware.ts
Two small touchups:
confluent kafka accidentally left out of 
As a matter of good habit, use @deprecated on removed code, so the compiler helps people catch problems quicker.
=> Fix publish; adjust deprecation

packages/dbos-kafkajs/index.ts, src/error.ts, src/system_database.ts, tests/wfqueue.test.ts
This PR addresses issue https://github.com/dbos-inc/dbos-transact-ts/issues/725 where duplicate workflow ID breaks the existing workflow. The solution is to check the recorded function name, class name, and config name (if any) before proceeding to start the workflow. If there's any difference, throw a `DBOSConflictingWorkflowError` with a clear error message.
This PR also checks the recorded input versus the provided input, and the provided queue name versus the original queue name, and print a warning message if they don't match.
=> Prevent different workflows starting with the same ID

dbos-config.schema.json, packages/create/templates/dbos-drizzle/dbos-config.yaml, packages/create/templates/dbos-knex/dbos-config.yaml, packages/create/templates/dbos-prisma/dbos-config.yaml, packages/create/templates/dbos-typeorm/dbos-config.yaml, src/dbos-runtime/cli.ts, src/dbos-runtime/config.ts, src/dbos-runtime/db_connection.ts, src/dbos-runtime/db_wizard.ts, src/dbos-runtime/migrate.ts, src/utils.ts, tests/dbos-runtime/config.test.ts
- Remove database connection parameters from `dbos-config.yaml` by default (though they can still be there)
- Instead, read and store database connection parameters in a hidden local file, `.dbos/db_connection`, which is **not committed to version control**.
- If no connection parameters are given, use local connection defaults.
- Clearly print where database connection parameters are being read from at DBOS startup.
=> Better Database Connection Parameter Management

migrations/20252101000000_workflow_queues_executor_id.js, schemas/system_db_schema.ts, src/system_database.ts, src/wfqueue.ts, tests/wfqueue.test.ts, tests/wfqueueworker.ts
- Implement worker concurrency limits for workflow queues. Same logic as in https://github.com/dbos-inc/dbos-transact-py/pull/177
- `worker_concurrency` is only available in a new constructor using an object as input -- much easier to use as we add arguments to the class.
Sanity check on the distributed test:
=> Queues max worker concurrency

src/dbos-executor.ts, src/error.ts, tests/failures.test.ts
If a step is configured with automatic retries, capture the error message thrown by each retry and include them as a property of the final error object thrown by the step.
Addresses https://github.com/dbos-inc/dbos-transact-ts/issues/724
=> Better Step Errors

src/system_database.ts
Use common try/catch/finally pattern to ensure transactions and connections are released.
See https://node-postgres.com/features/transactions
=> handle errors

src/dbos-executor.ts, src/dbos-runtime/workflow_management.ts, src/httpServer/server.ts, src/system_database.ts, tests/helpers.ts, tests/httpServer/adminserver.test.ts, tests/recovery.test.ts, tests/wfqueue.test.ts
- Cancelling a workflow removes it from any queue it is in. This way, cancelled workflows don't block queues.
- Resume sets status to `PENDING` and resets recovery attempts. It also removes the workflow from any queue it is in. This way, resume can safely start DLQ'ed, `CANCELLED`, and `ENQUEUED` workflows.
- Lots and lots of tests.
=> Test & Improve Queue Semantics

src/dbos-executor.ts, src/error.ts, src/system_database.ts, src/wfqueue.ts, src/workflow.ts, tests/helpers.ts, tests/recovery.test.ts, tests/wfqueue.test.ts
When performing recovery, we now re-enqueue workflows that came from a queue. This allows tasks from a queue to respect the concurrency limits.
Re-enqueue = reset the start time and executor assignment in the queue table. This ensures the task is re-inserted in the same position in the queue.
=> Fix queue recovery

src/dbos-runtime/migrate.ts, src/system_database.ts
This allows an older version of DBOS to start using a system database created by a later version, assuming all changes are backwards-compatible (as they should be).
=> Catch Exceptions During System Database Migration

src/system_database.ts, src/wfqueue.ts, src/workflow.ts, tests/wfqueue.test.ts, tests/wfqueueworker.ts
- Correctly retrieve the total number of tasks executed across all workers to compute the local limit
- When doing this query, do a `FOR UPDATE NO WAIT` to lock the rows -- and fail early when failing to do so.
- Adjusted the test `queued-wf-tests-concurrent-workers` test to enforce global concurrency.
=> Fix q global concurrency

package-lock.json, package.json, packages/dbos-cloud/cloudutils.ts, src/dbos-runtime/cli.ts, src/dbos-runtime/cloudutils/cloudutils.ts, src/dbos-runtime/config.ts, src/dbos.ts, src/telemetry/logs.ts, tests/logging.test.ts
Support the `forceConsole` option that was added in winston v3.14 to enable log output in the VSCode debug console. More info: https://github.com/winstonjs/winston?tab=readme-ov-file#routing-console-transport-messages-to-the-console-instead-of-stdout-and-stderr
=> Enable setting winston forceConsole in debug scenarios

src/dbos-executor.ts, src/dbos-runtime/cli.ts, src/dbos.ts, tests/helpers.ts, tests/testing/debugger.test.ts, tests/testing/debugger_configuredinst.test.ts
With the latest changes to parseConfigFile that uses env vars to override database connection info, the `DBOSConfig.debugProxy` field is no longer used. This PR removes it
=> remove obsolete debug proxy config field

package-lock.json, src/dbos-executor.ts, src/dbos.ts, src/decorators.ts, src/error.ts, src/httpServer/handler.ts, src/httpServer/server.ts, src/testing/testing_runtime.ts, src/workflow.ts, tests/baddecorator.ts, tests/contextfreeapi.test.ts
Detect conflicting decorators (can't use Transaction and Step together, for example)
Rename some things bearing vestiges of "communicator" terminology.
npm audit fix
=> Detect double decoration

tests/wfqueue.test.ts, tests/wfqueueworker.ts
The previous version of this test was relying on a sleep to wait for a task to be dequeued -- this proves flaky in GHA.
This PR modify the test to have:
1. Test worker send a notification each time a task is dequeued
2. Remove usage of sleep in the test
3. Wait for all the worker processes in a finally statement inside the test workflow. This ensures that we don't fail the `afterEach` system db shutdown, which in turn would fail the `beforeEach` statements of other tests.
=> do not rely on sleep

packages/dbos-cloud/applications/deploy-app-code.ts, tests/wfqueue.test.ts
- Actually compress application archives before uploading to DBOS Cloud
- Add some debugging information to track the state of the application upload
- Improve the error message when the compressed archive is too large (see bellow what the existing error looks like. Not exactly precise)
Old:
New:
=> Cloud cli actually compress and monitor

src/data_validation.ts, src/decorators.ts, tests/logging.test.ts
Phase 1 - relax reflect metadata requirement
Test pass.  With `emitDecoratorMetadata` turned off in tsconfig.json, the following tests fail (which is what we expect):
validation.test.ts - This test uses the metadata to do argument validation (in the rudimentary way we'd like to replace with something better in later phases of the project)
debug_typeorm.test.ts - TypeORM needs this setting
typeorm.test.ts - TypeORM needs this setting
=> Relax reflect-metadata requirement

src/system_database.ts, tests/helpers.ts, tests/scheduler/scheduler_contextfree.test.ts, tests/wfqueue.test.ts
Only use the `dbos.workflow_status.executor_id` column to represent queue assignments.
Also properly catch and display errors during test DB setup. See the difference:
Also relax the timing test for scheduled workflows (allow 2ms vs 2microseconds)
=> No duplicate executor id column

packages/dbos-cloud/applications/deploy-app-code.ts
When not handling explicitly errors thrown by inquirer, we don't have a chance to return a failure exit code. (GHA seems to force a 0.)
Without the fix:
With the fix
=> handle chooseAppDBServer errors and return a 1 exit code if it threw

packages/communicator-email-ses/README.md, packages/communicator-email-ses/ses.test.ts, packages/component-aws-s3/README.md, packages/component-aws-s3/src/s3_utils.test.ts, packages/dbos-confluent-kafka/README.md, packages/dbos-confluent-kafka/confluent-kafka.test.ts, packages/dbos-kafkajs/README.md, packages/dbos-kafkajs/kafkajs.test.ts, packages/dbos-sqs/README.md, packages/dbos-sqs/sqs.test.ts, src/dbos.ts, src/decorators.ts, tests/configuredinstances.test.ts, tests/contextfreeinst.test.ts, tests/recovery_configuredinst.test.ts, tests/testing/debugger_configuredinst.test.ts, tests/v2v1apimix.test.ts, tests/wfqueue.test.ts
Constructor works fine, world gets simpler.
Old code, and mixing with `configureInstance` is still fine, as configureInstance simply calls the constructor.
=> Make configureInstance optional

src/dbos-runtime/workflow_management.ts, src/system_database.ts, src/workflow.ts, tests/workflow_management.test.ts
Make sure TS accepts the same set of limiters as Python.
For listWorkflows, added:
- workflowIDs
- offset
- sortDesc
For listQueuedWorkflows, added:
- offset
- sortDesc
Also updated tests to thoroughly test those new limiters.
Next step: make sure the workflow information output matches the ones in Python.
=> Support sort order, offset, and workflow IDs in listWorkflows

.github/workflows/test.yml, packages/dbos-kafkajs/kafkajs.test.ts, src/dbos.ts, tests/proc-test/src/operations.test.ts, tests/proc-test/src/operations.ts, tests/testing/debug_typeorm.test.ts, tests/testing/debugger.test.ts, tests/testing/debugger_configuredinst.test.ts
This relies on only one DBOS running at a time (in the right mode for the situation), but otherwise the same.
=> Remove TestingRuntime from debugger tests

src/system_database.ts
I noticed that `SystemDatabase.checkWorkflowOutput` was incorrectly checking the status field and was going to fix it. However, @qianl15 noticed that the function isn't used anywhere so I changed this PR to delete the function entirely
=> remove sysdb checkWorkflowOutput 

src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts
Handle the case where `constructPoolConfig` has to derive an app DB name using the provided Config.
+ improve the log entry to use the problematic name
=> handle spaces in app name when building app db name

schemas/system_db_schema.ts, src/context.ts, src/dbos-executor.ts, src/system_database.ts, src/workflow.ts, tests/oaoo.test.ts, tests/workflow_management.test.ts
- Record `get_result` as a step (`DBOS.getResult`).
- Record child workflows in the `operation_outputs` table with the same name as in the `workflow_status` table.
- Eliminate some more uses of "external" in favor of "step".
- `getWorkflowSteps` should return deserialized results, to be consistent with the workflow introspection operations.
=> Record get_result as a step

package-lock.json, package.json, packages/dbos-confluent-kafka/index.ts, packages/dbos-kafkajs/index.ts, src/context.ts, src/dbos-executor.ts, src/dbos.ts, src/decorators.ts, src/index.ts, tests/configuredinstances.test.ts, tests/contextfreeinst.test.ts, tests/dbos.test.ts, tests/failures.test.ts, tests/proc-test/tsconfig.json, tests/recovery_configuredinst_v2.test.ts, tests/steptxqueue.test.ts, tests/testing/debugger.test.ts, tests/testing/debugger_configuredinst.test.ts
`InitContext` is already "optional" in the sense that you can leave that argument off your initialize methods.  You can just ask `DBOS` for stuff at init time ... make `InitContext` behave that way to prove it.
=> InitContext becomes optional

packages/dbos-cloud/applications/secrets.ts, packages/dbos-cloud/cli.ts, packages/dbos-cloud/databases/databases.ts
- Remove app rollback command
- Remove db local command
- Have db connect return a db string (password hidden by default) instead of modifying dbos-config.yaml
- Update secrets vocabulary to use "environment variables". See screenshots.
=> db connect returns dbString + remove rollback and local commands

src/dbos-executor.ts, src/eventreceiver.ts, src/system_database.ts, src/transaction.ts, src/user_database.ts, src/workflow.ts, tests/appversion.test.ts, tests/concurrency.test.ts, tests/configuredinstances.test.ts, tests/contextfreeapi.test.ts, tests/contextfreeinst.test.ts, tests/dbos-runtime/config.test.ts, tests/dbos.test.ts, tests/httpServer/adminserver.test.ts, tests/httpServer/server.test.ts, tests/httpserve_v2.test.ts, tests/oaoo.test.ts, tests/proc-test/src/operations.ts, tests/recovery.test.ts, tests/testing/debugger.test.ts, tests/wfqueue.test.ts, tests/workflow_management.test.ts
This PR removes pre-mature optimizations on workflow status/input buffering and read-only transactions.
- No more input buffering for single-transaction workflows.
- No more output buffering for all workflows. When a workflow returns a result, it is guaranteed that the workflow status is updated to `SUCCESS` with its output.
- Deprecate `readOnly` transactions.
- Fixed all the tests with the new behavior.
=> Remove buffers

dbos-config.schema.json, packages/create/templates/dbos-drizzle/drizzle.config.ts, packages/create/templates/dbos-knex/knexfile.js, packages/create/templates/dbos-typeorm/datasource.ts, src/client.ts, src/dbos-executor.ts, src/dbos-runtime/config.ts, src/dbos-runtime/migrate.ts, src/system_database.ts, src/user_database.ts, tests/client.test.ts, tests/dbos-runtime/config.test.ts, tests/dbos-runtime/runtime.test.ts, tests/drizzle.test.ts, tests/helpers.ts, tests/knex.test.ts, tests/pgnode.test.ts, tests/prisma.test.ts, tests/proc-test/knexfile.js, tests/stored-proc.test.ts, tests/typeorm.test.ts
This PR crafts connection strings to create user DB clients.
The key changes are:
- All ORMs use the connection string for config
- Except: connect_timeout and pool size, which must be given separately to be considered
- When the config provides a database url, pass it as is (except for debug user/password/host/port overrides if needed)
- When no url is provided, rebuild one from provided parameters and/or defaults
Notes:
- During DBOS Cloud overrides, craft a connection string from the config file. no-verify for linked databases (no ssl_ca), full-verify otherwise
- When a user provides a connection string, we do a little backfill of the poolConfig params for other parts of the code to keep working
- This PR enforces user / password / hostname / dbname are present in a connection string …
=> Use connection strings to configure user DB clients

src/dbos.ts
Fix a small bug in the DBOS initialization check used by the queue module to warn users if DBOS was already launched when they registered a new queue.
This only happens on the "DBOS runtime" path because it:
- creates an executor
- load the classes
- then calls init
Whereas the common path creates and initializes the executor at once (then load the classes).
**BEFORE:**
Shows up on the dbos runtime path:
does not show on the common path:
**AFTER THE FIX**
dbos runtime path:
common path still warns as expected
=> Fix is initialized

src/dbos-runtime/cli.ts
this doesn't fix the output of `steps` because it relies on launching a DBOS instance. This will be fixed in upcoming TS work.
=> silence logs when parsing config during workflow get and workflow steps

src/dbos-executor.ts, src/httpServer/server.ts, src/system_database.ts, tests/httpServer/adminserver.test.ts, tests/workflow_management.test.ts
This PR refactors the PG System DB class, looking to reduce places where we had duplicated code and improve reliability thru use of transactions.
Note, there are currently four locations in this PR where we begin a tx w/o specifying an isolation level. Should we specifying something *other* that READ COMMITTED for these?
Assorted Details
* extract queries used in multiple places into standalone functions
* prefix internal class methods with `#` 
* Use transactions in initWorkflowStatus
* calling `cancelWorkflow` on a completed workflow no longer changes the WF status
* more descriptive names in `SystemDatabaseStoredResult` and `recordOperationResult`
=> Refactor PG sysdb

src/client.ts, src/conductor/conductor.ts, src/dbos-executor.ts, src/dbos-runtime/workflow_management.ts, src/dbos.ts, src/eventreceiver.ts, src/httpServer/server.ts, tests/workflow_management.test.ts
Also modified `listWorkflowSteps` to return `undefined` for invalid WFIDs instead of an empty array, allowing callers to differentiate between an invalid WF and a WF that hasn't started executing yet.
=> add DBOS.listWorkflowSteps

src/conductor/conductor.ts, src/conductor/protocol.ts, src/httpServer/server.ts, src/system_database.ts, tests/httpServer/adminserver.test.ts, tests/workflow_management.test.ts
- Support `forkWorkflow` in conductor mode.
- Make resume throws `DBOSNonExistentWorkflowError` if the workflow doesn't exist.
=> Support fork in Conductor

src/dbos-runtime/runtime.ts, src/dbos.ts, src/httpServer/middleware.ts, src/testing/testing_runtime.ts, src/workflow.ts, tests/drizzle.test.ts, tests/httpServer/classdec.test.ts, tests/knex.test.ts, tests/pgnode.test.ts, tests/prisma.test.ts, tests/typeorm.test.ts, tests/wfqueue.test.ts
This PR makes the following DBOS static's private by prepending a `#`:
* #executor
* #runtimeConfig
* #invokeWrappers
* #runAsWorkflowStep
* #dbosConfig
Additional changes:
* removed `DBOS.globalLogger`. This was set in a couple places but was never read. the `DBOS.logger` property reads the logger from context, from executor or constructs a new GlobalLogger instance.
* added `DBOS.dbosConfig` getter. A couple places were setting this field - those have been updated to call `DBOS.setConfig`.
* added an exported functions `runAsWorkflowStep` and `getExecutor` to `dbos.ts` that can be used from other DBOS modules. Note, those exported functions are not part of the public API surface area exposed in `index.ts`.
=> remove undocumented parts of DBOS public surface area

src/context.ts, src/dbos-executor.ts, src/dbos.ts, src/error.ts, src/system_database.ts, src/workflow.ts, tests/client.test.ts, tests/dbos.test.ts, tests/wfcancel.test.ts, tests/wfqueue.test.ts
- Fix detaching children from parent timeout
- Fix recovery deadline overwrite
- `DBOSTargetWorkflowCancelledError` --> `DBOSAwaitedWorkflowCancelledError`
=> Fix recovery deadlines

src/system_database.ts
Make sure we convert `queue_name` to `undefined` when retrieving it from the database. Also updated the check to be more robust.
Closes #913
=> Fix warning message for recovery

package.json, packages/aws-config/package.json, packages/communicator-bcrypt/README.md, packages/communicator-bcrypt/package.json, packages/communicator-datetime/README.md, packages/communicator-datetime/package.json, packages/communicator-email-ses/README.md, packages/communicator-email-ses/package.json, packages/communicator-random/README.md, packages/communicator-random/package.json, packages/component-aws-s3/README.md, packages/component-aws-s3/package.json, packages/create/package.json, packages/dbos-cloud/package.json, packages/dbos-compiler/package.json, packages/dbos-confluent-kafka/README.md, packages/dbos-confluent-kafka/package.json, packages/dbos-kafkajs/README.md, packages/dbos-kafkajs/package.json, packages/dbos-sqs/README.md, packages/dbos-sqs/package.json, src/eventreceiver.ts, tests/httpServer/classdec.test.ts
Every little bit helps cut down the diff size w/ TSv3 branch:
- Mark parts of v1 event receiver interface as deprecated (use `DBOS.` instead)
- Comments
- Update repo URLs in packages
=> Trivial changes (taken from TSv3 branch)

migrations/20252528000000_consolidate_queues.js, schemas/system_db_schema.ts, src/client.ts, src/dbos-executor.ts, src/dbos.ts, src/eventreceiver.ts, src/index.ts, src/system_database.ts, src/testing/testing_runtime.ts, src/wfqueue.ts, src/workflow.ts, tests/client.test.ts, tests/contextfreeapi.test.ts, tests/contextfreeinst.test.ts, tests/helpers.ts, tests/stored-proc.test.ts, tests/wfqueue.test.ts
Move all functionality of the `workflow_queues` table to the `workflow_status` table. Optimize queries and add indexes.
Other changes:
- As priority-based sorting is expensive, disable it unless specifically requested.
- Fix an issue where priority was not implemented correctly for client.
- Remove `getWorkflowQueue` and always use `listQueuedWorkflows`
- Fix the issue where `EnqueueOptions` was defined twice.
Next step: Use DBOS library version to compute app version.
=> Faster Queues

src/dbos-runtime/config.ts, tests/dbos-runtime/config.test.ts
Do not require password to be set when the user explicitly pass in a database url.
This will not affect the behavior for other cases (e.g., config file).
=> Password not required in database_url

src/dbos.ts, tests/contextfreeapi.test.ts, tests/decorator-free.test.ts, tests/scheduler/scheduler.test.ts
Adds `DBOS.startWorkflowFunction` - like `DBOS.startWorkflow` for for registered workflows. 
Also adds a few missing JSDoc comments from previous PR and tests.
Note, there looks to be duplicate code between `@DBOS.step` and `registerStep` as well as between `startWorkflow`, `startWorkflowFunction` and `#proxyInvoke`. This will be DRYed out in a future PR.
Update: In the end, this PR DRYed out the multiple workflow invocation paths into a single function `DBOS.#invokeWorkflow`. Additional changes to DRY steps + improve `startWorkflowFunction` and improve `startWorkflow` support for registered workflows will come in later PRs.
=> startWorkflowFunction

src/dbos.ts, tests/decorator-free.test.ts
`startWorkflow` creates a proxy object from an existing class or class instance where the workflow methods return a WorkflowHandle. The previous proxy creation approach was dependent on the workflow's registered name being the same as the method name. With the new `registerWorkflow` API, the developer can choose whatever name they wish. Unless they pick the method name, `startWorkflow` no longer works. 
This PR modifies `startWorkflow` to use JS's native [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object. The proxy handler's `get` method first uses `getRegistrationForFunction` to retrieve the `MethodRegistration` for the workflow function. If this fails, `startWorkflow` falls back to matching on the workflow function name, as it did …
=> use Proxy/Reflect in startWorkflow

src/dbos.ts, tests/decorator-free.test.ts
Update the overloads and proxy returned from startWorkflow to handle free registered function workflows
Example usage:
```ts
function wfFunction(value: number) { /* implementation omitted */ }
const registeredWFFunction= DBOS.registerWorkflow(
wfFunction, 
'wfFunction');
// when using startWorkflow with a function, it returns a function;
const handle = await DBOS.startWorkflow(registeredWFFunction)(10);
```
=> update startWorkflow to handle free function registered workflows

src/telemetry/traces.ts
Ensure attributes exists on the span before setting them in `endSpan`
=> Handle attributes safely when ending spans

packages/knex-datasource/index.ts, packages/knex-datasource/tests/config.test.ts, packages/knex-datasource/tests/datasource.test.ts
* initializeInternalSchema -> initializeSchema
* add uninitializeSchema
* both init and uninit Schema functions can take either a Knex config or a Knex object (meaning it can be used from Knex migration files)
=> update knex db schema init/uninit functions

package.json
When running `npm install` locally I noticed the warning `husky - install command is DEPRECATED` in the output. Easy fix, simply replace `husky install` with just `husky` in the `prepare` NPM package script
=> replace deprecated husky install command

src/conductor/conductor.ts, src/conductor/protocol.ts, src/httpServer/server.ts, src/system_database.ts, src/workflow.ts, tests/httpServer/adminserver.test.ts, tests/workflow_management.test.ts
- Support not loading input/output of workflows in list workflows/queues. This improves performance when we want to list workflows with large input/output.
- By default admin endpoints and conductor skips input/output.
- Add tests.
=> List workflows/queues support skipping input/output

package-lock.json, src/client.ts, src/context.ts, src/datasource.ts, src/dbos-executor.ts, src/dbos.ts, src/eventreceiver.ts, src/httpServer/middleware.ts, src/httpServer/server.ts, src/system_database.ts, src/telemetry/logs.ts, src/user_database.ts, tests/dboslogger.test.ts, tests/logtodboslogger.ts, tests/workflow_management.test.ts
Add a test for the contextual information the logger is supposed to report.
Simplify this logger to get context dynamically, rather than creating new loggers.
Sanitize (IMO) the names of the loggers.
Fix the spans a bit, based on issues found by the test.
Also removes some dead stuff from package-lock.json
=> Add span to logger again, +test

packages/aws-s3-workflows/README.md, packages/aws-s3-workflows/src/s3_utils.test.ts, packages/aws-s3-workflows/src/s3_utils.ts, packages/confluent-kafka-receive/index.ts, packages/drizzle-datasource/index.ts, packages/kafkajs-receive/index.ts, packages/knex-datasource/index.ts, packages/koa-serve/README.md, packages/koa-serve/src/dboshttp.ts, packages/koa-serve/src/dboskoa.ts, packages/koa-serve/tests/argsource.test.ts, packages/koa-serve/tests/auth.test.ts, packages/koa-serve/tests/basic.test.ts, packages/koa-serve/tests/cors.test.ts, packages/koa-serve/tests/endpoints.test.ts, packages/koa-serve/tests/steps.test.ts, packages/koa-serve/tests/transactions.test.ts, packages/nodepg-datasource/index.ts, packages/postgres-datasource/index.ts, packages/sqs-receive/README.md, packages/typeorm-datasource/index.ts, src/datasource.ts, src/dbos.ts, src/decorators.ts, src/httpServer/handler.ts, src/index.ts, src/paramdecorators.ts, src/scheduler/scheduler.ts, tests/datasourceextensions.test.ts, tests/decorator-free.test.ts
Make naming options consistent.
Do not rely on names for steps, transactions in the new scheme; those names are not necessarily unique (no temp workflow constraint).
Fix a bug in step registration w/ other decorators.
registerLifecycleCallback called consistently by the library, not the user.
A few other registration cleanups.
=> Make registrations consistent

src/dbos-runtime/config.ts, src/telemetry/exporters.ts, src/utils.ts, tests/dbos-runtime/config.test.ts
The properties of `OTLPExporterConfig` were defined as `string[] | undefined` but the schema for `dbos-config.yaml` were defined as `string | undefined`. 
This PR updates `OTLPExporterConfig` properties to be `string | string[] | undefined` and modifies config parsing code to handle single strings and arrays of strings.
Also fixes an issue where we don't return the database url in `translatePublicDBOSconfig`
=> fix OTLPExporterConfig interface

.github/workflows/test.yml
Node 23 exited support June 2025
Note, odd number Node releases are only supported for about 8 months. Generally, production apps are only supposed to use supported LTS releases which are always even numbered. We add supported odd numbered versions to our test matrix primarily as a jump on the next LTS release. (i.e. if there's an issue w/ Node 23, it will also be an issue w/ Node 24).
=> Drop Node 23 from test matrix

src/conductor/conductor.ts, src/dbos-executor.ts, src/dbos-runtime/config.ts, src/dbos.ts, src/utils.ts, tests/dbos-runtime/config.test.ts
`translateDbosConfig` was dropping the app name on the floor. 
As part of this change, I removed `globalParams.appName` which was only used by `Conductor`. Since `Conductor` has a reference to DBOSExecutor, I added an `appName` getter to that.
=> Handle config.name correctly

src/dbos-runtime/cli.ts, src/dbos-runtime/migrate.ts, tests/dbos-runtime/runtime.test.ts
This command adds a new `dbos schema` CLI command to create DBOS system tables. Usage is:
```
Usage: dbos schema [options] [systemDatabaseUrl]
Create the DBOS system database and its internal tables
Arguments:
systemDatabaseUrl      System database URL
Options:
-d, --appDir <string>  Specify the application root directory
-h, --help             display help for command
````
This is most useful in settings where the application does not run with sufficient privilege to create the DBOS system database or system tables. Prior to deployment, the `dbos schema` command can be run with a privileged user to create DBOS system tables. Then, the application can run with a less privileged user that has access to the system database but does not need CREATE privileges.
=> New "dbos schema" CLI

src/dbos-runtime/cli.ts, src/dbos-runtime/migrate.ts, tests/dbos-runtime/runtime.test.ts, tests/migrate.test.ts
When creating the DBOS system tables with `npx dbos schema` you can now specify an "application role."
If you specify this role, it is granted all permissions needed to run a DBOS app.
```
Usage: dbos schema [options] [systemDatabaseUrl]
Create the DBOS system database and its internal tables
Arguments:
systemDatabaseUrl        System database URL
Options:
-d, --appDir <string>    Specify the application root directory
-r, --app-role <string>  The role with which you will run your DBOS application
-h, --help               display help for command
```
This is most useful in settings where the application runs with an "application role" that does not have sufficient privileges to create the DBOS system database or system tables. Prior to deployment, the dbos migrate command can be run with …
=> Migration Permissions

migrations/20252806000000_streaming.js, schemas/system_db_schema.ts, src/client.ts, src/dbos.ts, src/system_database.ts, src/workflow.ts, tests/streaming.test.ts
This PR adds an API for streaming data from workflows.
```ts
/**
* Write a value to a stream.
* @param key - The stream key/name within the workflow
* @param value - A serializable value to write to the stream
*/
async writeStream<T>(key: string, value: T): Promise<void>
/**
* Close a stream by writing a sentinel value.
* @param key - The stream key/name within the workflow
*/
async closeStream(key: string): Promise<void>
/**
* Read values from a stream as an async generator.
* This function reads values from a stream identified by the workflowID and key,
* yielding each value in order until the stream is closed or the workflow terminates.
* @param workflowID - The workflow instance ID that owns the stream
* @param key - The stream key/name within the workflow
* @returns An async …
```
=> Streaming API

src/conductor/conductor.ts
superjson produces a different string when stringified, which breaks the conductor protocol.
This PR just uses normal JSON for sending conductor responses.
All the input/output deserialization is done at the protocol layer, before a response is sent.
=> Use normal JSON to format conductor responses

src/client.ts, src/config.ts, src/dbos-executor.ts, src/sysdb_migrations/migration_runner.ts, src/system_database.ts, tests/dbos.test.ts
You can now pass in a custom `node-postgres` pool through DBOS configuration. If a pool is passed in, DBOS **exclusively** uses it to access the system database; it does not construct any pool of its own.
```typescript
const systemDatabaseURL = ...
const pool = new Pool({ connectionString: systemDatabaseURL });
const config: DBOSConfig = {
name: "my-dbos-app"
systemDatabaseUrl: systemDatabaseURL,
systemDatabasePool: pool,
};
DBOS.setConfig(config);
await DBOS.launch();
```
=> Custom Pool
