package-lock.json

https://github.com/advisories/GHSA-67hx-6x53-jw92

update @babel/traverse dependency

---

src/operon-runtime/config.ts
tests/operon-runtime/config.test.ts

- add default values for `connectionTimeoutMillis` and `user_dbclient`
- update unit tests to verify these are applied

Add some default configuration values

---

src/operon.ts

~FYI, more commits coming - missed the default roles~

emit required roles / endpoint on operon start

---

.github/workflows/publish_npm.yml

Need to publish this branch from Github actions.

Add Github action from main branch

---

.github/workflows/publish_npm.yml

fix release tag

---

src/cloud-cli/cli.ts
src/cloud-cli/delete.ts
src/cloud-cli/deploy.ts
src/cloud-cli/monitor.ts
src/cloud-cli/register.ts

Gives the cloud CLI a port argument in addition to its host argument.

Cloud CLI Port

---

src/cloud-cli/cli.ts

Should use `DEFAULT_PORT` in CLI.

Fix a CLI bug

---

src/cloud-cli/applications/register-app.ts

A small PR to adjust a log entry in the operon-cloud CLI

update log entry

---

src/cloud-cli/applications/delete-app.ts
src/cloud-cli/applications/deploy-app-code.ts
src/cloud-cli/applications/get-app-logs.ts
src/cloud-cli/applications/list-apps.ts
src/cloud-cli/applications/register-app.ts
src/cloud-cli/applications/update-app.ts
src/cloud-cli/cli.ts

Cloud CLI application commands now return non-zero exit codes on failure.

Exit Codes

---

src/workflow.ts

This PR inserts multiple rows into transcation_outputs when flushing the result buffer. This reduces the number of round trips to the remote DB.

Insert multiple rows into transaction outputs

---

src/context.ts
src/dbos-runtime/runtime.ts
src/debugger/debug_workflow.ts
src/httpServer/handler.ts
src/httpServer/server.ts
src/workflow.ts
tests/concurrency.test.ts
tests/dbos.test.ts
tests/foundationdb/fdb_oaoo.test.ts
tests/oaoo.test.ts
tests/recovery.test.ts

This was supposed to be delivered as part of the rename checkin, but I found some unsaved files in vs.code waaaaay to the right in the tab panel.

Rename wfe to dbosExec

---

src/dbos-executor.ts
src/debugger/debug_workflow.ts
src/system_database.ts

This PR updates the executor to also connect to the debug proxy for the system database (the proxy can support both user DB and system DB now).
This PR also updates to use a better existence check when initializing the system DB in Postgres.

Debug mode for system DB

---

src/cloud-cli/applications/deploy-app-code.ts
src/cloud-cli/userdb.ts

Title is self descriptive. Tested with integration test on a baremetal machine.

use recommended prune flag and suppress warning

---

src/cloud-cli/applications/deploy-app-code.ts

At deploy time, automatically insert OTel exporters configuration, pointing to an endpoint we know.
✅ Tested in DBOS cloud

inject otlp exporter config at deploy

---

src/cloud-cli/userdb.ts

`npx` is not supported inside the Firecracker VMs for now.

Fix Migration Command

---

examples/hello/dbos-config.yaml
src/cloud-cli/applications/configure.ts
src/cloud-cli/cli.ts
src/cloud-cli/userdb.ts
src/dbos-runtime/config.ts

- Eliminate usage of unsafe API endpoints
- Delete no longer needs to block

Improve User Database Experience

---

src/dbos-executor.ts
tests/testing/debugger.test.ts

This PR adds two checks for the debug mode workflow execution: 1) check the input is the same as the recorded one, otherwise throw an error; 2) check the output is the same as the recorded one, and log the error if they are different.
This PR also adds a test to verify the implementation.

Check Debug Mode Input and Output

---

src/cloud-cli/applications/list-apps.ts
src/cloud-cli/applications/types.ts

Companion PR for https://github.com/dbos-inc/dbos-cloud/pull/152

Fix Application Status

---

examples/hello/dbos-config.yaml
src/cloud-cli/applications/delete-app.ts
src/cloud-cli/applications/deploy-app-code.ts
src/cloud-cli/applications/get-app-logs.ts
src/cloud-cli/applications/register-app.ts
src/cloud-cli/applications/update-app.ts
src/cloud-cli/cli.ts

Companion PR to https://github.com/dbos-inc/dbos-cloud/pull/154

Application Names

---

src/cloud-cli/applications/deploy-app-code.ts

Companion PR to https://github.com/dbos-inc/dbos-cloud/pull/157

 Deploys Waits for Availability

---

src/cloud-cli/applications/deploy-app-code.ts
src/cloud-cli/utils.ts
src/httpServer/server.ts

Before deploying an application to the cloud, build it in a local Docker container using the base same image as the DBOS Cloud Firecracker microVMs.

Docker-based Build in Deploy

---

.github/workflows/artifact.yml
.github/workflows/publish_npm.yml
.github/workflows/test.yml
examples/hello/.eslintignore
examples/hello/.eslintrc
examples/hello/knexfile.ts
examples/hello/package.json
examples/hello/src/operations.ts
examples/hello/tsconfig.json
package-lock.json
package.json

Also fix the lint issues it found
Update koa/cors types (dependabot fixed a vuln but missed the types I think)

Initialize lint in hello example

---

src/cloud-cli/applications/deploy-app-code.ts
src/httpServer/server.ts
src/telemetry/logs.ts
src/telemetry/traces.ts

Adds a health check route at `/dbos-healthz`

Health Checks

---

src/cloud-cli/applications/delete-app.ts
src/cloud-cli/applications/deploy-app-code.ts
src/cloud-cli/applications/get-app-logs.ts
src/cloud-cli/applications/list-apps.ts
src/cloud-cli/applications/register-app.ts
src/cloud-cli/applications/update-app.ts
src/cloud-cli/register.ts
src/cloud-cli/utils.ts

Improving DBOS Cloud error messages

Better Errors

---

.github/workflows/test.yml
examples/hello/start_postgres_docker.sh

Run all the SDK tests in Postgres 16.1.

Postgres 16.1

---

migrations/20240123182943_schema.js
migrations/20240123183021_tables.js
migrations/20240123183025_indexes.js
migrations/20240123183030_triggers.js
packages/dbos-cloud/userdb.ts
src/dbos-runtime/migrate.ts
src/system_database.ts
src/utils.ts

Use Knex migrations for system database tables, making it easier to change these tables in the future.

System Database Migration

---

packages/dbos-cloud/applications/delete-app.ts
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/get-app-logs.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/applications/update-app.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/login.ts
packages/dbos-cloud/register.ts
packages/dbos-cloud/tsconfig.json
packages/dbos-cloud/userdb.ts
src/utils.ts

This PR eliminates all dependencies of the Cloud CLI on the SDK, making builds more robust.

Eliminate Cloud CLI Dependencies on SDK

---

.github/workflows/publish_npm.yml
package-lock.json
packages/communicator-bcrypt/index.ts
packages/communicator-bcrypt/package.json
packages/communicator-bcrypt/tsconfig.json
packages/communicator-datetime/index.ts
packages/communicator-datetime/package.json
packages/communicator-datetime/tsconfig.json
packages/communicator-random/index.ts
packages/communicator-random/package.json
packages/communicator-random/tsconfig.json
packages/dbos-cloud/package.json
packages/dbos-openapi/tsconfig.json

Communicator library packages for nondeterministic functions: date, random, bcrypt.
NPM publish: less cut-n-paste.

ND Functions communicator library

---

src/dbos-runtime/cli.ts
src/dbos-runtime/migrate.ts
src/telemetry/exporters.ts

PR to address Max's comments to my last PR :). Apologies.
Ran `prettier` on migrate.ts. Moved the `runAndLog` routine to cli.ts. Cleaned up the callback-wait-promise for exports. Note the comment I made there: https://github.com/dbos-inc/dbos-ts/pull/263/files#r1467966387

Max's comments

---

packages/dbos-cloud/applications/delete-app.ts
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/get-app-logs.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/applications/update-app.ts
packages/dbos-cloud/cli.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/register.ts
packages/dbos-cloud/userdb.ts

- Better handle API errors, specifically, uses a type guard to check whether the error comes from the API.
- Handle return codes in `userdb` commands
With DBOS cloud down:

Better api error handling

---

packages/dbos-cloud/userdb.ts

Spotted a typo while working with the CLI today

Fix a typo in a logger message

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/login.ts

Companion PR to https://github.com/dbos-inc/dbos-cloud/pull/286

Production Auth0

---

packages/dbos-cloud/applications/get-app-info.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/types.ts
packages/dbos-cloud/cli.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/userdb.ts
src/dbos-runtime/migrate.ts

Companion to https://github.com/dbos-inc/dbos-cloud/pull/295
Additionally, print an error when using an expired JWT token

New Metadata Commands

---

src/dbos-executor.ts

Now we can deploy TypeORM apps to the cloud.

Fix ssl setting for typeorm

---

package-lock.json
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/cli.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/login.ts
packages/dbos-cloud/register.ts
packages/dbos-cloud/userdb.ts

- The login command no longer takes in a username--instead, you authenticate with DBOS Cloud and it retrieves your username if you have an account. 
- Miscellaneous command output improvements.

Improve Cloud Login

---

examples/hello/migrations/20240212161006_create_dbos_hello_tables.js

Add new tables for the SDK programming guide.
Tested with all DBOS cloud integration tests, using `npx -y @dbos-inc/dbos-sdk@test init`

Update hello example

---

package-lock.json
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/get-app-info.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/types.ts
packages/dbos-cloud/cli.ts
src/dbos-runtime/config.ts

Companion to https://github.com/dbos-inc/dbos-cloud/pull/331

Server-Side Build + Bugfixes

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/dashboards.ts

Client API call for GetDashboardURL

Get Dashboard URL implementation

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/dashboards.ts
src/dbos-executor.ts
src/dbos-runtime/cli.ts
src/dbos-runtime/config.ts
src/dbos-runtime/debug.ts
src/dbos-runtime/runtime.ts
src/error.ts

Add PRs to this patch:
- Better error handling for debug mode CLI (#311)
- Get Dashboard URL implementation (#312)

Release v0.10 patch1

---

examples/hello/.vscode/extensions.json
examples/hello/.vscode/launch.json
examples/hello/.vscode/tasks.json
package-lock.json
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/package.json
packages/dbos-cloud/register.ts

This patch includes four commits:
- Fix DBOS Cloud Dependency (#321)
- Improve Application Hosting (#320) 
- add local debug config to example/hello (#319)
- Add vscode files to template (#318)

Release v0.11 patch1

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/userdb.ts

This is the companion PR to https://github.com/dbos-inc/dbos-cloud/pull/356 which allows users to reset their Postgres user password in case they forget.
```
Usage: dbos-cloud database reset-password [options] <name>
Reset password for a Postgres database instance
Arguments:
name                     database instance name
Options:
-W, --password <string>  Specify the database user password
-h, --help               display help for command
```
Will update the docs soon.

Reset db password

---

src/debugger/debug_workflow.ts
tests/testing/debugger.test.ts

Need to properly increment function ID for sleep in debug mode. Added a test case for it.

Fix sleep in debug mode

---

src/dbos-runtime/init.ts

Ensure `init` always installs the latest versions of the SDK and Cloud CLI

Init @latest

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/cli.ts

Add a new command to ask the cloud for a DB rollback. Under the hood, this does exactly the same think than deploy but performs the `rollback` commands listed in `dbos-config.yaml`

Add a rollback command

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/cloudutils.ts

This PR prompts a hint (in red) for users when they try to deploy an app without registering it first, or when they try to register an app without provisioning a DB first.

Hint for non-existent app and db

---

src/httpServer/server.ts

This PR exposes an admin API endpoint to query event loop utilization.

Perf Endpoint

---

packages/dbos-cloud/dashboards.ts
packages/dbos-cloud/login.ts

Should we also do this for `dashboard launch` and `dashboard url`?

enable open for login command

---

.gitignore
README.md
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/cloudutils.ts

[v1.0 patch] Changes to support Windows (#342) 

---

packages/dbos-cloud/userdb.ts

Reduce wait time to 5 second for the first iteration

Fast DB provisioning

---

packages/dbos-openapi/openApi.ts
packages/dbos-openapi/tsconfig.json

Help prevent missing case handling logic when new enum variant is added.

(refactor) Add compile-time switch case exhaustiveness check

---

README.md
dbos-config.schema.json
package.json
packages/communicator-bcrypt/package.json
packages/communicator-datetime/package.json
packages/communicator-random/package.json
packages/create/package.json
packages/dbos-cloud/package.json
packages/dbos-openapi/package.json
src/dbos-executor.ts
src/dbos-runtime/config.ts
src/dbos-runtime/migrate.ts
src/dbos-runtime/runtime.ts

- Allow configuring the system database name
- Better reporting of initialization errors
- Clean up metadata

Configurable System Database

---

src/httpServer/server.ts

This PR addresses the issue https://github.com/dbos-inc/dbos-transact/issues/381 by providing better error logging when we check port availability.
We now log the error separately for IPv4 and IPv6 checks and provide detailed error stack.

Better error logging for check port availability

---

packages/dbos-cloud/userdb.ts

Remove references to the deprecated `AdminUsername` field.

Cleanup DB Management API

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/userdb.ts

This is the companion PR to enable "bring your own RDS" (BYOD) to DBOS Cloud.

BYOD Commands

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/login.ts
packages/dbos-cloud/profile.ts

A new DBOS Cloud command that lets you retrieve information about yourself (for now, registered name, email, and subscription status).

Profile Command

---

packages/dbos-openapi/cli.ts

allow the processing of many entrypoints from the dbos-openapi CLI

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/cli.ts

Initial support for restoring old application versions.  Redeploys a previous version with a specified version number.  Directly deploys the original code of that version, so make sure your database schema is what that version expects!

Deploy Old Versions

---

packages/dbos-cloud/applications/delete-app.ts

Modify the cloud CLI delete command to wait for the application to be fully deleted before succeeding.

Cloud CLI Synchronous Delete

---

dbos-config.schema.json
packages/create/templates/hello/dbos-config.yaml
src/dbos-runtime/config.ts
tests/dbos-runtime/config.test.ts

The database username `dbos` conflicts with our internal `dbos` schema and should be disallowed.  Addresses https://github.com/dbos-inc/dbos-transact/issues/410

Validate Database Username

---

dbos-config.schema.json
src/context.ts
src/dbos-executor.ts
src/dbos-runtime/config.ts
src/dbos-runtime/configure.ts
src/debugger/debug_workflow.ts
src/httpServer/handler.ts
src/testing/testing_runtime.ts
src/utils.ts
src/workflow.ts
tests/dbos-runtime/config.test.ts
tests/helpers.ts

Revisit config types

---

src/dbos-executor.ts

This PR fixes a race condition where the buffer is being flushed when we destroy the DBOS executor. I saw sometimes the testRuntime would throw errors like `Error flushing workflow inputs buffer...` after tests. This is not an issue for normal execution because we never call `destroy` but could be confusing to see destroy errors in tests or debug mode.
- Make sure we don't have two concurrent `flushWorkflowBuffers()` running by using the `isFlushingBuffers` flag.
- Make sure we wait for buffers to be exported before destroying `systemDatabase`.

Fix buffer flush race condition in destroy()

---

packages/dbos-cloud/applications/get-app-versions.ts
packages/dbos-cloud/applications/list-app-versions.ts
packages/dbos-cloud/applications/types.ts
packages/dbos-cloud/cli.ts

Get a list of all previously deployed versions of your application:
```
npx dbos-cloud app versions <app-name> [--json]
```

Get Application Versions

---

src/decorators.ts
src/index.ts
tests/httpServer/validation.test.ts

Remove deprecated Debug decorator

---

packages/communicator-bcrypt/README.md
packages/communicator-datetime/README.md
packages/communicator-random/README.md

README.md seems nice to have because of the npm pages.  (Currently only documented in our docs in the reference section.)

Readmes for the comm libs

---

packages/dbos-cloud/databases/databases.ts

Validate DBOS Cloud database passwords client-side.  Addresses https://github.com/dbos-inc/dbos-transact/issues/430

Database Password Validation

---

.editorconfig
packages/dbos-cloud/applications/delete-app.ts
packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/get-app-info.ts
packages/dbos-cloud/applications/get-app-logs.ts
packages/dbos-cloud/applications/list-app-versions.ts
packages/dbos-cloud/applications/list-apps.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/cloudutils.ts
packages/dbos-cloud/dashboards/dashboards.ts
packages/dbos-cloud/databases/databases.ts
packages/dbos-cloud/users/login.ts
packages/dbos-cloud/users/register.ts

Org routing:
- All cloud API routes now use the organization name instead of the username
Retrieving the organization name
- Org Name is now present in .dbos/credentials. In the normal path (login), organization name is retrieved from DBOS Cloud API.
- During registration, we also get the user profile and update the credentials file

Organization routing

---

packages/dbos-cloud/applications/deploy-app-code.ts

(ignore info lines that are debug in the PR)

allow yarn.lock and disable both package-json.lock and yarn.lock

---

packages/dbos-cloud/cli.ts
packages/dbos-cloud/organizations/organization.ts

The new command is:
`npx dbos-cloud org join <organization> <secret>`

dbos cloud command for users to join an organization

---

packages/dbos-openapi/openApi.ts
src/dbos-executor.ts
src/httpServer/handler.ts
src/httpServer/handlerTypes.ts
src/httpServer/server.ts
src/utils.ts
tests/httpServer/server.test.ts

This PR adds support for  PUT PATCH and DELETE http methods.
I have not yet implemented any tests.
I will go about writing them  later in the week
If possible it would be nice if someone from the team provided stubs of the required tests

implement PUT/PATCH/DELETE handlers

---

package-lock.json
packages/create/templates/hello-prisma/package-lock.json
packages/create/templates/hello-prisma/src/operations.ts

Removed an unnecessary casting to `PrismaClient`.
Also updated package-lock.json file which seems to include unused S3 dependencies.

Simplify prisma template

---

packages/dbos-cloud/applications/index.ts
packages/dbos-cloud/applications/types.ts
packages/dbos-cloud/cli.ts
packages/dbos-cloud/dashboards/dashboards.ts
packages/dbos-cloud/databases/databases.ts
packages/dbos-cloud/users/authentication.ts
packages/dbos-cloud/users/profile.ts

Applies editorconfig rules to dbos cloud package

apply .editorconfig rules

---

src/index.ts
tests/httpServer/server.test.ts

This PR resolves #494
Missed that!
What about a test like this?
```ts
import {
ArgSource,
GetApi,
PostApi,
PatchApi,
PutApi,
DeleteApi } from '../src';
describe("test public exports", () => {
test("dummy", () => {
expect(true).toBe(true)
});
});
```

export handler decorators

---

src/index.ts
tests/httpServer/server.test.ts

This PR resolves #494
Missed that!
---------

export handler decorators (#495)

---

.github/workflows/publish_npm.yml
package-lock.json

SES and AWSConfig were not on the published package list.

Publish AWS

---

package-lock.json
packages/communicator-email-ses/package.json

Only occurred in publish workflow

Didn't compile - missing dep

---

packages/component-aws-s3/src/s3_utils.ts

Arguments were supposed to be optional but weren't always acting that way.

AWS S3 Fix w/ Optional Arguments

---

packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts

This PR adds an `npx dbos-cloud workflows list` command analogous to [`npx dbos workflows list`](https://docs.dbos.dev/api-reference/cli#npx-dbos-workflow-list) but in the cloud.

DBOS Cloud ListWorkflows

---

packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts

ListWorkflows is now filterable by workflow UUID so you can retrieve a specific workflow.

Better Cloud ListWorkflows

---

packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts

This PR adds support for skipping a number of workflows when listing workflows.
Also fixes a bug where the `workflowUUIDs` parameter wasn't passed in correctly.

Support offset/skip for list workflows

---

src/dbos-executor.ts
src/dbos-runtime/config.ts
tests/dbos-runtime/config.test.ts

This PR fixes https://github.com/dbos-inc/dbos-transact/issues/549

Undefined environment variables should be empty strings

---

packages/create/templates/hello-prisma/src/operations.ts
packages/create/templates/hello-typeorm/src/operations.ts
packages/create/templates/hello/src/operations.ts
packages/dbos-openapi/tests/openapi.test.ts

This should be an easier guide for users to reach the greeting/:name route. And a good example of serving up HTML

Seed the "Hello" app with a readme at the / route.

---

packages/dbos-cloud/applications/deploy-app-code.ts

remove yarn.lock check during deploy

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/applications/register-app.ts
packages/dbos-cloud/cloudutils.ts

Language-aware Registration

---

src/scheduler/scheduler.ts
tests/scheduler/scheduler.test.ts

Test the workflow makeup modes

---

src/dbos-executor.ts
src/decorators.ts
tests/drizzle.test.ts

I think it deleted my old PR when I reset. Pretty sure the formatting issues have been addressed, as well as the other concerns. Let mw know if there's anything else. Thanks!

Add Support for Drizzle Relational Queries

---

packages/create/init.ts

Use YAML.parseDocument as inspired by https://github.com/dbos-inc/dbos-transact/pull/583

Better way to preserve comments in create

---

src/dbos-runtime/config.ts
src/system_database.ts
tests/dbos-runtime/config.test.ts

The check was too restrictive.

Fix db name length check

---

src/dbos-runtime/workflow_management.ts
tests/workflow_management.test.ts

Fix an issue where ListWorkflows improperly handled workflows that threw an error. Add a test for this case.

Fix ListWorkflows

---

packages/dbos-sqs/index.ts
packages/dbos-sqs/sqs.test.ts

Should have checked the payload more deeply in unit test.

Fix and test for #605

---

packages/dbos-cloud/applications/deploy-app-code.ts

Deploy perf1 - shave ~ 5secs of deploy time

---

packages/dbos-cloud/applications/deploy-app-code.ts

handle registration failure during deploy

---

packages/create/templates/hello-drizzle/package.json
packages/create/templates/hello-prisma/package.json
packages/create/templates/hello-typeorm/package.json
packages/create/templates/hello/package.json
tests/dbos-runtime/runtime.test.ts

Also add `npm run lint` to our runtime tests.

Upgrade @dbos-inc/eslint-plugin to the latest version 3.3.4.

---

src/error.ts
src/foundationdb/fdb_system_database.ts
src/system_database.ts
tests/dbos.test.ts

Allow set event multiple times

---

packages/dbos-compiler/templates/dbos.create.liquid
tests/proc-test/src/operations.test.ts
tests/proc-test/src/operations.ts

Support no param queries in @StoredProcs

---

packages/dbos-kafkajs/README.md
packages/dbos-kafkajs/index.ts
packages/dbos-sqs/README.md
packages/dbos-sqs/index.ts
src/kafka/kafka.ts
src/scheduler/scheduler.ts
src/testing/testing_runtime.ts
tests/scheduler/scheduler.test.ts

Allow scheduled/kafka/sqs workflows to be enqueued.
Test infrastructure to help get workflow info from testing runtime.

Queues integration for event receivers

---

tests/v2api.test.ts

when I run the tests on my local WSL machine, where the repo dir is in `~/ts-transact`, the tests in `v2api.test` fails because it's emitting to `../../dist`, which is outside of my home directory and so don't have correct permissions w/o using sudo. This PR changes the outDir to be relative to the tests directory and to clean up the generated code after the test

absolute outDir path for v2api.test

---

src/dbos.ts
tests/contextfreeapi.test.ts

Make ms the default, with seconds available via separate function.

Sleep API v2

---

packages/create/templates/hello-nextjs/README.md
packages/create/templates/hello-nextjs/src/actions/dbosWorkflow.tsx
packages/create/templates/hello-nextjs/src/app/crash/route.ts
packages/create/templates/hello-nextjs/src/app/page.tsx
packages/create/templates/hello-nextjs/src/app/step/[slug]/route.ts
packages/create/templates/hello-nextjs/src/app/tasks/[slug]/route.ts
packages/create/templates/hello-nextjs/src/components/client/BackGroundTask.tsx

Changed the nextjs template to be the "start background job" "Crash application app"

Nextjs background Job template

---

package-lock.json
package.json
packages/create/templates/hello-drizzle/README.md
packages/create/templates/hello-drizzle/package.json
packages/create/templates/hello-drizzle/src/operations.test.ts
packages/create/templates/hello-drizzle/src/operations.ts
packages/create/templates/hello-express/README.md
packages/create/templates/hello-nextjs/README.md
packages/create/templates/hello-prisma/README.md
packages/create/templates/hello-prisma/src/operations.test.ts
packages/create/templates/hello-prisma/src/operations.ts
packages/create/templates/hello-typeorm/README.md
packages/create/templates/hello-typeorm/src/operations.test.ts
packages/create/templates/hello-typeorm/src/operations.ts
packages/create/templates/hello-v2/README.md
src/dbos.ts

Also allow idempotency key in send.

Update API use and URLs in example templates

---

src/step.ts

More intuitive default behavior for TSv2.

Steps Shouldn't Retry By Default

---

package-lock.json
src/dbos-executor.ts
src/system_database.ts
src/wfqueue.ts

Fix an issue where the executor ID of a dequeued workflow was that of the enqueuing executor, not the dequeuing executor.

Fix Queues

---

packages/dbos-confluent-kafka/confluent-kafka.test.ts
packages/dbos-confluent-kafka/index.ts
packages/dbos-kafkajs/index.ts
packages/dbos-kafkajs/kafkajs.test.ts

Also confluent kafka was missing queues.

Adjust kafka workflow IDs

---

src/dbos-runtime/cli.ts
src/dbos-runtime/reset.ts

Db reset command

---

src/dbos-executor.ts
tests/dbos-runtime/runtime.test.ts

This was removed in https://github.com/dbos-inc/dbos-transact-ts/pull/697. Re-enabling it and adding tests.

Create App Database if Does Not Exist

---

src/dbos-executor.ts
src/dbos.ts
tests/testing/debug_launch.test.ts

updates DBOS.launch to read DBOS_DEBUG_WORKFLOW_ID and DBOS_DEBUG_PROXY environment variables for debug scenarios

V2 Library Debugging

---

src/httpServer/server.ts

/dbos-workflows/:workflow_id/cancel
/dbos-workflows/:workflow_id/resume
/dbos-workflows/:workflow_id/restart

Workflow admin api

---

src/httpServer/server.ts

renamed to start with /workflows

rename urls for wf admin apis

---

.husky/pre-commit
packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts
src/dbos-runtime/cli.ts
src/dbos-runtime/config.ts
src/dbos-runtime/workflow_management.ts
src/system_database.ts
src/workflow.ts
tests/wfqueue.test.ts
tests/workflow_management.test.ts

CLI utility for listing the contents of your queues, both locally and in DBOS Cloud.

List Queues

---

src/dbos-executor.ts
tests/testing/debugger.test.ts

The error messages for step, transaction, and procedure were wrong.

Fix the wrong error message

---

package-lock.json
package.json

https://github.com/advisories/GHSA-593f-38f6-jp5m

Update Koa dependency to 2.15.4

---

packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts
src/dbos-runtime/cli.ts

Cloud CLI for workflow cancel, resume, and restart commands. Same semantics as locally.

Workflow Management Cloud CLI

---

src/dbos-runtime/cli.ts
src/dbos-runtime/workflow_management.ts
src/httpServer/server.ts
tests/workflow_management.test.ts

Make workflow cancel/restart/resume cli use the admin api

Workflow cmd cli fix

---

packages/dbos-cloud/applications/manage-workflows.ts
packages/dbos-cloud/cli.ts

Allow specifying the sort order when listing workflows or queued workflows.

Better Workflows List

---

packages/dbos-cloud/applications/deploy-app-code.ts

Hurts compatibility with other package managers.

remove lockfile constraint during node app deploys

---

src/conductor/conductor.ts
src/conductor/protocol.ts

- Reduce handshake timeout to 5 seconds.
- Support adding an error message to the websocket response.
- Properly handle all possible exceptions.
- Handle unknown message types.

Support error message in conductor

---

packages/component-aws-s3/src/s3_utils.ts
src/dbos-executor.ts
src/dbos.ts
src/system_database.ts
tests/failures.test.ts
tests/helpers.ts
tests/steptxqueue.test.ts
tests/wfqueue.test.ts
tests/wfqueueworker.ts

Also some better errors for calling startWorkflow on unregistered functions

Enqueue transactions and steps

---

src/conductor/conductor.ts
src/conductor/protocol.ts

- Display executor hostname
- Return executor ID for workflows

Conductor Tweaks

---

src/client.ts
tests/client.test.ts

replace two phase construction (ctor + init) with `static async create` method

static async ctor for DBOS Client

---

src/dbos-executor.ts
src/dbos-runtime/config.ts
src/system_database.ts
tests/contextfreeapi.test.ts
tests/dbos-runtime/config.test.ts
tests/dbos.test.ts
tests/drizzle.test.ts
tests/helpers.ts
tests/knex.test.ts
tests/pgnode.test.ts
tests/prisma.test.ts
tests/typeorm.test.ts

- Allow sizing user db pool
- Fix usage of connect_timeout

Config poolsize and appdbconnecttimeout

---

schemas/system_db_schema.ts
src/dbos-executor.ts
src/dbos-runtime/workflow_management.ts
src/httpServer/server.ts
src/system_database.ts
tests/httpServer/adminserver.test.ts
tests/workflow_management.test.ts

(1) admin API for list steps
(2) changes for compatibility with python

Step adminapi

---

tests/tsconfig.json

Reverts dbos-inc/dbos-transact-ts#816

Revert "add a tsconfig file to tests folder to share compiler settings with the rest of the code base"

---

src/conductor/conductor.ts

- Send a `ping` to Conductor every 20 seconds. If it doesn't receive a response within 15 seconds, the connection is considered lost.
- If the connection is lost, reset all resources and schedule a reconnect to the Conductor.

Implement ping pong with Conductor

---

packages/create/templates/dbos-drizzle/dbos-config.yaml
packages/create/templates/dbos-prisma/dbos-config.yaml
packages/create/templates/dbos-typeorm/dbos-config.yaml
src/dbos.ts
src/httpServer/server.ts
tests/httpServer/adminserver.test.ts

Do not crash when unable to start the admin server

---

src/dbos-runtime/reset.ts

Have reset db CLI command use the internal PostgresSystemDatabase.dropSystemDB function
Note the internal function *does not* terminate existing connection -- which is a good thing.

Consolidate sysdb reset code

---

src/dbos.ts
src/decorators.ts
src/wfqueue.ts

warn users when a queue is constructed post DBOS launch

---

src/context.ts
src/dbos.ts
src/decorators.ts
src/httpServer/handler.ts
src/index.ts
src/procedure.ts
src/step.ts
src/testing/testing_runtime.ts
src/transaction.ts
src/workflow.ts

DBOS class gets JSDocs
Old API gets deprecation warnings
Will continue to expand set of JSDocs.

First installment of JSDocs

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/cli.ts

improve Cloud CLI DB url description

---

package-lock.json
packages/communicator-email-ses/README.md
packages/dbos-confluent-kafka/index.ts
packages/dbos-kafkajs/index.ts
packages/dbos-sqs/index.ts
src/dbos-executor.ts
src/dbos.ts
src/eventreceiver.ts
src/scheduler/scheduler.ts
src/system_database.ts
tests/eventreceiver.test.ts

Reduce complexity a little, use `DBOS` in a manner consistent with other APIs.

Clean EventRec API

---

packages/dbos-cloud/databases/databases.ts

It should connect to the postgres database, which always exists.

Fix DB Connect

---

src/httpServer/server.ts
tests/httpServer/classdec.test.ts

on nested routes
See issue here: https://github.com/dbos-inc/dbos-transact-ts/issues/852

Prevent Koa middleware from being invoked multiple times 

---

src/dbos-runtime/config.ts
src/system_database.ts
tests/dbos-runtime/config.test.ts

bump connect timeout to 10s

---

dbos-config.schema.json
src/dbos-executor.ts
src/dbos-runtime/config.ts
tests/dbos-runtime/config.test.ts

similar to https://github.com/dbos-inc/dbos-transact-py/pull/301

deprecate json fields and accept null values

---

src/dbos-executor.ts
src/dbos.ts
src/eventreceiver.ts
src/httpServer/server.ts
src/system_database.ts
src/utils.ts
src/wfqueue.ts
tests/httpServer/adminserver.test.ts
tests/recovery.test.ts
tests/wfcancel.test.ts
tests/wfqueue.test.ts
tests/workflow_management.test.ts

Update restart and resume to use the internal Q

Internal queue

---

src/dbos-executor.ts
src/dbos.ts
src/eventreceiver.ts
src/system_database.ts
tests/workflow_management.test.ts

(1) Be able to call fork with WithNextWOrkflowId
(2) Provide app version as an optional param

Fork id version

---

src/system_database.ts
tests/wfqueue.test.ts

Fix an issue where workflows of the wrong version count against worker concurrency limits.

Worker Concurrency Fix

---

src/wfqueue.ts

add a queue ctor with only the name parameter

---

src/dbos.ts
src/transactionsource.ts
tests/datasourceextensions.test.ts

* remove MethodRegistration param from invokeTransactionFunction
* Add config option to runAsWorkflowTransaction

minor tx updates

---

tests/drizzle.test.ts

Use all v2
Try a serializable tx conflict.

Improve Drizzle Test

---

src/dbos-runtime/workflow_management.ts
src/httpServer/server.ts
src/system_database.ts
tests/httpServer/adminserver.test.ts
tests/workflow_management.test.ts

Methods to delete the history of old completed workflows and set a global timeout for workflows.

Workflow Retention

---

.github/workflows/publish_npm.yml
package-lock.json
packages/koa-serve/README.md
packages/koa-serve/jest.config.js
packages/koa-serve/package.json
packages/koa-serve/src/dboshttp.ts
packages/koa-serve/src/dboskoa.ts
packages/koa-serve/src/index.ts
packages/koa-serve/tests/argsource.test.ts
packages/koa-serve/tests/auth.test.ts
packages/koa-serve/tests/basic.test.ts
packages/koa-serve/tests/cors.test.ts
packages/koa-serve/tests/endpoints.test.ts
packages/koa-serve/tests/validation.test.ts
packages/koa-serve/tsconfig.json
src/authdecorators.ts
src/dbos.ts
src/decorators.ts
src/index.ts
src/paramdecorators.ts

Has the functionality that was built into TSv2 but as a self-contained external package.
Was tried out on a branch of widget store: https://github.com/dbos-inc/dbos-demo-apps/tree/chuck/tsv3.

Koa serving external package

---

packages/dbos-sqs/README.md
src/conductor/conductor.ts
src/conductor/protocol.ts
src/dbos-runtime/workflow_management.ts
src/dbos.ts
src/httpServer/server.ts
src/system_database.ts
tests/httpServer/adminserver.test.ts
tests/workflow_management.test.ts

Pulls over non v3 commits from main into the `release/v2.10` branch for public release.
* Workflow Retention (#940)
* Retention policy in Conductor (#944)
* Add workflow get list admin enpoints (#943)
* fix: missing period in README.md (#952)
* add deprecated JSDoc to both DBOS.invoke overloads (#954)

Cherry picked commits for release

---

packages/confluent-kafka-receive/index.ts
packages/confluent-kafka-receive/tests/confluent-kafka.test.ts
packages/kafkajs-receive/index.ts
packages/kafkajs-receive/tests/kafkajs.test.ts

Kafka Improvements

---

jest.config.js
packages/confluent-kafka-receive/README.md
packages/confluent-kafka-receive/index.ts
packages/confluent-kafka-receive/tests/confluent-kafka.test.ts
packages/drizzle-datasource/tests/datasource.test.ts
packages/kafkajs-receive/README.md
packages/kafkajs-receive/index.ts
packages/kafkajs-receive/tests/kafkajs.test.ts
packages/knex-datasource/tests/datasource.test.ts
packages/koa-serve/src/dboshttp.ts
packages/nodepg-datasource/tests/datasource.test.ts
packages/postgres-datasource/tests/datasource.test.ts
packages/sqs-receive/index.ts
packages/sqs-receive/sqs.test.ts
packages/typeorm-datasource/tests/datasource.test.ts
src/dbos.ts
tests/datasourceextensions.test.ts
tests/decorator-free.test.ts
tests/eventreceiver_v3.test.ts
tests/jsapi.test.js
tests/stepfuncs.test.ts

Make registerWorkflow name consistent with step and tx
Test for straight JavaScript

WF registration + JS test

---

src/httpServer/server.ts
tests/httpServer/adminserver.test.ts

Make it consistent with ListWorkflows and Conductor/Cloud.

GetWorkflow admin endpoint returns WorkflowsOutput

---

.gitignore
packages/create/init.ts
packages/create/templates/dbos-drizzle/src/main.ts
packages/create/templates/dbos-knex/src/main.ts
packages/create/templates/dbos-typeorm/src/main.ts

TODO: install `release` versions after we officially release TS v3.

Install correct dependencies

---

chaos-tests/workflows.test.ts

I set it to 1000 while I was diagnosing the issue. Didn't mean to commit that.

fix chaos test iterations

---

package-lock.json
package.json
packages/koa-serve/package.json

https://github.com/koajs/router/pull/181#issuecomment-3024902625

update koa router dependency

---

packages/dbos-cloud/applications/deploy-app-code.ts
packages/dbos-cloud/cloudutils.ts

(1) dbos-cloud app deploy
from root dir
config file needed in that dir
(2) dbos-cloud app deploy --configFile ....

deploy Java app

---

.github/workflows/on_pr.yml
.github/workflows/on_push.yml
README.md

Fix Node version badge display
